In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("encuestas_concatenadas.xlsx")

In [3]:
df

,encuestadora,fecha,factor,departamento,municipio,region,zona,genero,edad_grupo,estrato,...,sv_cepeda_vs_lizcano,sv_cepeda_vs_murillo,sv_cepeda_vs_pinzon,sv_cepeda_vs_uribe_londono,sv_cepeda_vs_valencia,sv_espriella_vs_fajardo,sv_espriella_vs_valencia,sv_fajardo_vs_pinzon,sv_fajardo_vs_valencia,aprobacion_petro
0,Atlas Intel,2026-01-09,2.650916e-06,Santander,Barichara,Central,NaN,Hombre,45-59,NaN,...,NaN,NaN,Voto en blanco,NaN,Iván Cepeda,Sergio Fajardo,NaN,NaN,NaN,Regular
1,Atlas Intel,2026-01-09,6.110878e-07,Antioquia,Medellín,Central,NaN,Hombre,60+,NaN,...,NaN,NaN,Voto en blanco,NaN,Voto en blanco,Voto en blanco,NaN,NaN,NaN,Malo / muy malo
2,Atlas Intel,2026-01-09,7.076182e-07,Antioquia,Medellín,Central,NaN,Hombre,35-44,NaN,...,NaN,NaN,Juan Carlos Pinzón,NaN,Paloma Valencia,Sergio Fajardo,NaN,NaN,NaN,Malo / muy malo
3,Atlas Intel,2026-01-09,7.413255e-07,Antioquia,Medellín,Central,NaN,Mujer,60+,NaN,...,NaN,NaN,Juan Carlos Pinzón,NaN,Voto en blanco,Sergio Fajardo,NaN,NaN,NaN,Malo / muy malo
4,Atlas Intel,2026-01-09,6.080302e-07,Antioquia,Caldas,Central,NaN,Hombre,35-44,NaN,...,NaN,NaN,Voto en blanco,NaN,Voto en blanco,Voto en blanco,NaN,NaN,NaN,Malo / muy malo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44512,CNC,2026-03-16,5.157391e+03,HUILA,Timaná,Centro - Sur - Amazonía,Urbana,Mujer,35-44,2,...,Ninguno,Ninguno,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa
44513,CNC,2026-03-16,2.642461e+04,RISARALDA,Pereira,Eje Cafetero,Urbana,Mujer,35-44,3,...,Mauricio Lizcano,Luis Gilberto Murillo,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa
44514,CNC,2026-03-16,2.966080e+04,RISARALDA,Pereira,Eje Cafetero,Urbana,Hombre,35-44,3,...,Mauricio Lizcano,Luis Gilberto Murillo,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa
44515,CNC,2026-03-16,2.633356e+04,"BOGOTÁ, D.C.","Bogotá, D.C.",Bogotá,Urbana,Hombre,35-44,2,...,Iván Cepeda,Iván Cepeda,NaN,Iván Cepeda,Iván Cepeda,NaN,NaN,NaN,NaN,Positiva
44516,CNC,2026-03-16,2.196748e+04,"BOGOTÁ, D.C.","Bogotá, D.C.",Bogotá,Urbana,Hombre,55+,5,...,Iván Cepeda,Iván Cepeda,NaN,Iván Cepeda,Iván Cepeda,NaN,NaN,NaN,NaN,Positiva

In [4]:
df["encuestadora"]=df["encuestadora"].replace({"Invamer (Colombia Opina 21)": "Invamer","Invamer (Colombia Opina 20)": "Invamer"}, inplace=True)

C:\Users\pablo\AppData\Local\Temp\ipykernel_28772\3794612711.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df["encuestadora"]=df["encuestadora"].replace({"Invamer (Colombia Opina 21)": "Invamer","Invamer (Colombia Opina 20)": "Invamer"}, inplace=True)

In [5]:
df["encuestadora"].value_counts()

encuestadora
Atlas Intel    26194
Invamer         7602
CNC             5841
GAD3            4880
Name: count, dtype: int64

In [6]:

# Columnas de voto disponibles en el archivo
PREGUNTAS = [
    'primera_vuelta', 'primera_vuelta_espontanea',
    'sv_cepeda_vs_espriella', 'sv_cepeda_vs_fajardo', 'sv_cepeda_vs_valencia',
    'sv_espriella_vs_fajardo', 'sv_fajardo_vs_valencia', 'sv_espriella_vs_valencia',
    'sv_cepeda_vs_pinzon', 'sv_fajardo_vs_pinzon',
    'sv_cepeda_vs_claudia', 'sv_cepeda_vs_davila', 'sv_cepeda_vs_galan',
    'sv_cepeda_vs_gaviria', 'sv_cardenas_vs_cepeda', 'sv_barreras_vs_cepeda',
    'sv_cepeda_vs_lizcano', 'sv_cepeda_vs_murillo', 'sv_cepeda_vs_uribe_londono',
    'aprobacion_petro',
]
PREGUNTAS = [p for p in PREGUNTAS if p in df.columns]

def pcts(subdf, pregunta):
    validos = subdf[subdf[pregunta].notna()]
    if validos.empty:
        return None
    res = validos.groupby(pregunta)['factor'].sum()
    return (res / res.sum() * 100).round(1).sort_values(ascending=False)

def revisar(encuestadora, fecha=None):
    """Muestra % ponderados por pregunta. Siempre separado por fecha."""
    mask = df['encuestadora'] == encuestadora
    if fecha:
        mask &= df['fecha'].astype(str).str.startswith(str(fecha)[:10])
    sub = df[mask]
    if sub.empty:
        print('Sin datos'); return

    for f, grupo in sub.groupby('fecha'):
        f_str = str(f)[:10]
        print(f"\n{'='*58}\n  {encuestadora}  |  {f_str}  (n={len(grupo):,})\n{'='*58}")
        for preg in PREGUNTAS:
            serie = pcts(grupo, preg)
            if serie is None:
                continue
            print(f"\n  [{preg}]")
            for val, p in serie.items():
                bar = '█' * int(p / 2)
                print(f"    {str(val):<35} {p:>5.1f}%  {bar}")

In [7]:
# Surveys disponibles
df.groupby(['encuestadora','fecha']).size().rename('n').reset_index().sort_values(['encuestadora','fecha'])

   encuestadora      fecha     n
0   Atlas Intel 2026-01-09  4520
1   Atlas Intel 2026-02-05  7298
2   Atlas Intel 2026-02-28  6468
3   Atlas Intel 2026-03-12  4291
4   Atlas Intel 2026-04-10  3617
5           CNC 2026-02-20  3684
6           CNC 2026-03-16  2157
7          GAD3 2026-01-13  1207
8          GAD3 2026-02-16  2473
9          GAD3 2026-03-16  1200
10      Invamer 2026-02-25  3801
11      Invamer 2026-04-25  3801

In [8]:
# Atlas Intel — por fecha
revisar('Atlas Intel')

==========================================================
  Atlas Intel  |  2026-01-09  (n=4,520)
==========================================================

  [primera_vuelta]
    Abelardo de la Espriella             28.0%  ██████████████
    Iván Cepeda                          26.5%  █████████████
    Sergio Fajardo                        9.4%  ████
    Voto en blanco                        7.2%  ███
    No sé                                 5.7%  ██
    Juan Carlos Pinzón                    5.1%  ██
    Paloma Valencia                       5.1%  ██
    Claudia López                         2.6%  █
    Enrique Peñalosa                      2.3%  █
    Juan Daniel Oviedo                    1.8%
    Aníbal Gaviria                        1.3%
    Juan Manuel Galán                     1.1%
    No votaría                            1.1%
    David Luna                            0.9%
    Vicky Dávila                          0.9%
    Daniel Quintero                       0.4%
    Mauricio Cárdenas                     0.4%
    Roy Barreras                          0.2%
    Daniel Palacios                       0.0%

  [sv_cepeda_vs_espriella]
    Abelardo de la Espriella             44.2%  ██████████████████████
    Iván Cepeda                          34.9%  █████████████████
    Voto en blanco                       10.6%  █████
    No sé                                10.3%  █████

  [sv_cepeda_vs_fajardo]
    Sergio Fajardo                       39.6%  ███████████████████
    Iván Cepeda                          32.1%  ████████████████
    Voto en blanco                       17.9%  ████████
    No sé                                10.4%  █████

  [sv_cepeda_vs_valencia]
    Paloma Valencia                      38.2%  ███████████████████
    Iván Cepeda                          35.8%  █████████████████
    Voto en blanco                       13.9%  ██████
    No sé                                12.1%  ██████

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             37.9%  ██████████████████
    Voto en blanco                       27.3%  █████████████
    Sergio Fajardo                       23.2%  ███████████
    No sé                                11.6%  █████

  [sv_cepeda_vs_pinzon]
    Iván Cepeda                          36.4%  ██████████████████
    Juan Carlos Pinzón                   31.9%  ███████████████
    Voto en blanco                       20.4%  ██████████
    No sé                                11.4%  █████

  [aprobacion_petro]
    Malo / muy malo                      42.4%  █████████████████████
    Excelente / bueno                    29.9%  ██████████████
    Regular                              27.7%  █████████████

==========================================================
  Atlas Intel  |  2026-02-05  (n=7,298)
==========================================================

  [primera_vuelta]
    Abelardo de la Espriella             28.4%  ██████████████
    Iván Cepeda                          27.8%  █████████████
    No sé                                 7.7%  ███
    Sergio Fajardo                        6.7%  ███
    Blanco                                4.7%  ██
    Voto en blanco                        3.9%  █
    Paloma Valencia                       3.4%  █
    Claudia López                         3.3%  █
    Miguel Uribe Londoño                  1.9%
    Vicky Dávila                          1.7%
    Juan Daniel Oviedo                    1.5%
    Juan Carlos Pinzón                    1.5%
    Daniel Quintero                       1.4%
    Juan Manuel Galán                     1.1%
    Enrique Peñalosa                      1.1%
    Aníbal Gaviria                        1.0%
    Santiago Botero                       0.9%
    David Luna                            0.8%
    Camilo Romero                         0.7%
    Roy Barreras                          0.3%
    Juan Fernando Cristo                  0.1%
    Daniel Palacios                       0.1%
    Mauricio Cárdenas                     0.1%

  [primera_vuelta_espontanea]
    Iván Cepeda                          45.1%  ██████████████████████
    Abelardo de la Espriella             23.8%  ███████████
    Abelardo                              5.6%  ██
    Paloma Valencia                       3.6%  █
    Sergio Fajardo                        3.5%  █
    Carlos Caicedo                        1.9%
    Santiago Botero                       1.0%
    Abelardo de las prella                1.0%
    Abelardo de la aspriella              0.9%
    Claudia López                         0.8%
    Juan Daniel Oviedo                    0.8%
    Aspriella                             0.7%
    Juan Manuel Galán                     0.7%
    Abelardo delasprilla                  0.7%
    Delas priella                         0.5%
    Pinson                                0.5%
    Iván ceoeda                           0.5%
    David Luna                            0.5%
    Aspriel                               0.4%
    Abelardo de la Espirella              0.3%
    Abelardo Asprilla                     0.3%
    Juan Carlos Pinzón                    0.3%
    No dice                               0.3%
    Abelardo de la Asprilla               0.3%
    Abelardo de la spriella               0.3%
    Prueba                                0.3%
    Vicky Dávila                          0.3%
    Viki de avila                         0.3%
    Abelardo de la Espriellla             0.3%
    Secreto                               0.2%
    Abelardo aspriella                    0.2%
    De la aspriella                       0.2%
    Ivan                                  0.2%
    Abelardo de la Esprilla               0.2%
    Reserva                               0.2%
    Aníbal Gaviria                        0.2%
    Abelardo de la aspreilla              0.2%
    No quiero a este presidente           0.1%
    Carolina corcho (si se sube en la consulta)   0.1%
    Pacto  histórico                      0.1%
    Daniel Quintero                       0.1%
    Es privado                            0.1%
    Enrique peñaloza                      0.1%
    Enrique Peñalosa                      0.1%
    No se dice                            0.1%
    Anibal                                0.1%
    Camilo Romero                         0.1%
    Santiago Jaramillo                    0.1%
    Abelardo De la  Aspriella             0.1%
    Abelardo asp                          0.1%
    Miguel Barreto                        0.1%
    Miguel Uribe                          0.1%
    Me gusta la propuesta                 0.1%
    Abelardo de la esprella               0.1%
    Pacto histórico                       0.1%
    Abelardo de laspriella                0.1%
    Abelardo la aspreilla                 0.1%
    Apelando de la Espriellla             0.1%
    Apoya las ideas de petro              0.1%
    Quiero que sea nuestro presidente     0.1%
    NS/NR                                 0.0%
    No se                                 0.0%
    No se acuerda                         0.0%
    No quiere                             0.0%
    Miguel Uribe Londoño                  0.0%
    No informa                            0.0%
    No veo el problema del país           0.0%
    Menos por la izquierda                0.0%
    No votaría                            0.0%
    Nos dice que va a ver un buen cambio en el país   0.0%
    Mira                                  0.0%
    Puede a ver un cambio para Colombia   0.0%
    Paolama                               0.0%
    Partido los templarios                0.0%
    Viky                                  0.0%
    Tiene buenas propuestas               0.0%
    Supuestamente va por buen camino      0.0%
    Sigue el legado de petro              0.0%
    Si Petro se postula voto por el       0.0%
    Sepeda                                0.0%
    Se lo recerba                         0.0%
    Roy barrera                           0.0%
    Roy Barreras                          0.0%
    Reservado                             0.0%
    Que cambie la situación               0.0%
    Puede componer el país y mejores oportunidades   0.0%
    Me llama la atención sus propuestas   0.0%
    Por qué tiene buenas propuestas       0.0%
    Por quien vaya al frente en encuestas de la oposición   0.0%
    Por el que quede de la izquierda      0.0%
    Por el que diga Petro                 0.0%
    Por el qud diga petro                 0.0%
    Por el mismo de Petro                 0.0%
    Peñaloza                              0.0%
    Petro                                 0.0%
    Perro                                 0.0%
    Pasto histórico                       0.0%
    Mejoría en la educación               0.0%
    A elbelardo de laarso esprella        0.0%
    Me gustan sus propuestas              0.0%
    Es bueno                              0.0%
    El que le sigue a Petro               0.0%
    El mejor                              0.0%
    E gistasu hoja de vida                0.0%
    Defensora de la patria                0.0%
    Con la persona que baya con petro     0.0%
    Carolina corcho                       0.0%
    Blanco                                0.0%
    Asprilla                              0.0%
    Anival Gabiria                        0.0%
    Alvaro uribe                          0.0%
    Al que diga Petro                     0.0%
    Ablando de la esprilla                0.0%
    Aberlardo                             0.0%
    Abelardo de la priella                0.0%
    Abelardo de la estríela               0.0%
    Abelardo de la espteoella             0.0%
    Abelardo de la esprilla               0.0%
    Abelardo de la esprellaa              0.0%
    Abelardo de la eapriella              0.0%
    Abelardo de la apriella               0.0%
    Abelardo de la Espiriella             0.0%
    Abelardo de aspriella                 0.0%
    Abelardo de La Esprilla               0.0%
    Abelardo de                           0.0%
    Abelardo De la Spriella               0.0%
    El que ponga Petro                    0.0%
    Es el mejor                           0.0%
    Me gustamucho lo que quiere hacer     0.0%
    Es mejor candidato                    0.0%
    Me gusta su trayectoria política y du trabajo con la comunidad   0.0%
    Me gusta su trayectoria               0.0%
    Me gusta que fuera el presidente      0.0%
    Me gusta mucho                        0.0%
    Me gusta                              0.0%
    Mauricio Cárdenas                     0.0%
    Le gusta las propuestas del aspirante   0.0%
    Laspriella                            0.0%
    Juan Fernando Cristo                  0.0%
    Jp                                    0.0%
    Izquierda                             0.0%
    Iván cepeeda                          0.0%
    Iván cepada                           0.0%
    Iván                                  0.0%
    Indeciso                              0.0%
    Hay más oportunidades                 0.0%
    Hay muy mala administración           0.0%
    Gustavo petro                         0.0%
    Gustavo perro                         0.0%
    Gustavo Petro                         0.0%
    Federico                              0.0%
    Excelente propuesta                   0.0%
    Esprella                              0.0%
    Es secreto, no informa                0.0%
    Es muy preparado                      0.0%
    quien puntee de la derecha            0.0%

  [sv_cepeda_vs_espriella]
    Abelardo de la Espriella             36.8%  ██████████████████
    Iván Cepeda                          34.6%  █████████████████
    Voto en blanco                       16.9%  ████████
    No sé                                11.8%  █████

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          33.7%  ████████████████
    Sergio Fajardo                       26.2%  █████████████
    Voto en blanco                       26.2%  █████████████
    No sé                                14.0%  ███████

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          35.2%  █████████████████
    Paloma Valencia                      26.9%  █████████████
    Voto en blanco                       24.1%  ████████████
    No sé                                13.9%  ██████

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             31.8%  ███████████████
    Voto en blanco                       29.3%  ██████████████
    Sergio Fajardo                       21.7%  ██████████
    No sé                                17.2%  ████████

  [sv_cepeda_vs_pinzon]
    Iván Cepeda                          35.8%  █████████████████
    Voto en blanco                       28.9%  ██████████████
    Juan Carlos Pinzón                   18.8%  █████████
    No sé                                16.4%  ████████

  [aprobacion_petro]
    Malo / muy malo                      38.1%  ███████████████████
    Excelente / bueno                    35.6%  █████████████████
    Regular                              26.3%  █████████████

==========================================================
  Atlas Intel  |  2026-02-28  (n=6,468)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          34.0%  █████████████████
    Abelardo de la Espriella             31.9%  ███████████████
    Sergio Fajardo                        6.3%  ███
    Voto en blanco                        4.5%  ██
    Blanco                                4.4%  ██
    Paloma Valencia                       3.9%  █
    No sé                                 3.7%  █
    Vicky Dávila                          1.9%
    Claudia López                         1.8%
    Daniel Quintero                       1.5%
    Aníbal Gaviria                        1.0%
    Santiago Botero                       0.8%
    Roy Barreras                          0.8%
    Juan Carlos Pinzón                    0.8%
    Miguel Uribe Londoño                  0.7%
    Juan Manuel Galán                     0.7%
    Juan Daniel Oviedo                    0.6%
    Enrique Peñalosa                      0.2%
    Mauricio Cárdenas                     0.2%
    Mauricio Lizcano                      0.1%
    David Luna                            0.1%
    Daniel Palacios                       0.0%
    Juan Fernando Cristo                  0.0%

  [primera_vuelta_espontanea]
    Iván Cepeda                          43.9%  █████████████████████
    Abelardo de la Espriella             25.9%  ████████████
    Abelardo                              4.4%  ██
    Paloma Valencia                       4.3%  ██
    Aspriella                             2.8%  █
    Sergio Fajardo                        2.5%  █
    Derecha                               1.8%
    Ivan                                  1.7%
    De la aspriella                       1.5%
    Reserva                               1.4%
    Vicky Dávila                          1.3%
    Juan Carlos Pinzón                    0.9%
    Santiago Botero                       0.9%
    Roy Barreras                          0.7%
    Claudia López                         0.7%
    No dice                               0.6%
    Abelardo de aspriella                 0.5%
    Abelardo de la Espirella              0.5%
    Abelardo de la Esprilla               0.4%
    Juan Manuel Galán                     0.4%
    Aníbal Gaviria                        0.4%
    Laspriella                            0.4%
    Carlos Caicedo                        0.3%
    Abelardo de la Espriellla             0.2%
    Abelardo de la Asprilla               0.2%
    Abelardo de la aspriella              0.2%
    Abelardo de la asprilla               0.2%
    Estoy seguro                          0.1%
    Enrique peñaloza                      0.1%
    David Luna                            0.1%
    Pinilla                               0.1%
    Daniel Quintero                       0.1%
    Juan Daniel Oviedo                    0.1%
    Ana Paola                             0.1%
    Abelardo de las prella                0.1%
    Uribe                                 0.1%
    Iván                                  0.1%
    Miguel Uribe Londoño                  0.0%
    Miguel uribe                          0.0%
    NS/NR                                 0.0%
    Nlmmencikna                           0.0%
    Petro                                 0.0%
    No informa                            0.0%
    No información                        0.0%
    No voy a votar                        0.0%
    Pacto histórico                       0.0%
    Vicky                                 0.0%
    Mi voto es personal                   0.0%
    Roy barrera                           0.0%
    Ruben Marino                          0.0%
    Sergio                                0.0%
    Miguel Uribe                          0.0%
    Ivan crpeda                           0.0%
    Mauricio Lizcano                      0.0%
    El tigre de la aspriella              0.0%
    Abelardo de la Spriella               0.0%
    Abelardo de la espeiella              0.0%
    Abelardo de la espriela               0.0%
    Abelardo de las priellas              0.0%
    Abelardo de laspriella                0.0%
    Abelarod                              0.0%
    Avelardo de la  Aspriella             0.0%
    Blanco                                0.0%
    Daniel                                0.0%
    El que diga petro                     0.0%
    Enrique Peñalosa                      0.0%
    Mauricio Cárdenas                     0.0%
    Federico Gutierrez                    0.0%
    Gustavo petro                         0.0%
    Ivan c peda                           0.0%
    Ivan c.                               0.0%
    Ivan cepedq                           0.0%
    Iván cepada                           0.0%
    Iván cepefa                           0.0%
    Iván crpeda                           0.0%
    Juan  carlos pinzo                    0.0%
    Juan Daniel                           0.0%
    Vicky davika                          0.0%

  [sv_cepeda_vs_espriella]
    Abelardo de la Espriella             39.1%  ███████████████████
    Iván Cepeda                          38.9%  ███████████████████
    Voto en blanco                       15.3%  ███████
    No sé                                 6.7%  ███

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          37.5%  ██████████████████
    Voto en blanco                       25.7%  ████████████
    Sergio Fajardo                       25.1%  ████████████
    No sé                                11.7%  █████

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          39.8%  ███████████████████
    Paloma Valencia                      29.6%  ██████████████
    Voto en blanco                       20.7%  ██████████
    No sé                                10.0%  █████

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             34.7%  █████████████████
    Voto en blanco                       31.2%  ███████████████
    Sergio Fajardo                       19.9%  █████████
    No sé                                14.3%  ███████

  [sv_cepeda_vs_pinzon]
    Iván Cepeda                          40.7%  ████████████████████
    Voto en blanco                       26.9%  █████████████
    Juan Carlos Pinzón                   19.3%  █████████
    No sé                                13.1%  ██████

  [aprobacion_petro]
    Malo / muy malo                      37.1%  ██████████████████
    Excelente / bueno                    33.3%  ████████████████
    Regular                              29.6%  ██████████████

==========================================================
  Atlas Intel  |  2026-03-12  (n=4,291)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          35.0%  █████████████████

In [9]:
# GAD3 — por fecha
revisar('GAD3')

==========================================================
  GAD3  |  2026-01-13  (n=1,207)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          30.3%  ███████████████
    Abelardo de la Espriella             21.9%  ██████████
    NS/NR                                14.0%  ███████
    Ninguno                              10.6%  █████
    Voto en blanco                        5.0%  ██
    Paloma Valencia                       3.1%  █
    Juan Manuel Galán                     2.1%  █
    Juan Carlos Pinzón                    1.7%
    Vicky Dávila                          1.7%
    Sergio Fajardo                        1.3%
    Juan Daniel Oviedo                    1.1%
    Aníbal Gaviria                        1.1%
    Otro                                  1.0%
    Santiago Botero                       1.0%
    María Fernanda Cabal                  0.8%
    Camilo Romero                         0.7%
    Roy Barreras                          0.7%
    Enrique Peñalosa                      0.5%
    Germán Vargas Lleras                  0.4%
    Claudia López                         0.4%
    Mauricio Cárdenas                     0.3%
    Mauricio Lizcano                      0.1%

  [primera_vuelta_espontanea]
    Iván Cepeda                          30.3%  ███████████████
    Abelardo de la Espriella             21.9%  ██████████
    NS/NR                                14.0%  ███████
    Ninguno                              10.6%  █████
    Voto en blanco                        5.0%  ██
    Paloma Valencia                       3.1%  █
    Juan Manuel Galán                     2.1%  █
    Juan Carlos Pinzón                    1.7%
    Vicky Dávila                          1.7%
    Sergio Fajardo                        1.3%
    Juan Daniel Oviedo                    1.1%
    Aníbal Gaviria                        1.1%
    Otro                                  1.0%
    Santiago Botero                       1.0%
    María Fernanda Cabal                  0.8%
    Camilo Romero                         0.7%
    Roy Barreras                          0.7%
    Enrique Peñalosa                      0.5%
    Germán Vargas Lleras                  0.4%
    Claudia López                         0.4%
    Mauricio Cárdenas                     0.3%
    Mauricio Lizcano                      0.1%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          40.2%  ████████████████████
    Abelardo de la Espriella             31.9%  ███████████████
    Voto en blanco                       10.8%  █████
    No votaría                            9.6%  ████
    NS/NR                                 7.5%  ███

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          39.5%  ███████████████████
    Sergio Fajardo                       25.4%  ████████████
    No votaría                           15.3%  ███████
    Voto en blanco                       12.1%  ██████
    NS/NR                                 7.6%  ███

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          43.0%  █████████████████████
    Paloma Valencia                      20.1%  ██████████
    No votaría                           14.8%  ███████
    Voto en blanco                       13.9%  ██████
    NS/NR                                 8.1%  ████

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             31.7%  ███████████████
    Voto en blanco                       21.2%  ██████████
    No votaría                           19.5%  █████████
    Sergio Fajardo                       18.6%  █████████
    NS/NR                                 9.0%  ████

  [sv_fajardo_vs_valencia]
    Sergio Fajardo                       27.7%  █████████████
    Voto en blanco                       25.5%  ████████████
    No votaría                           21.8%  ██████████
    Paloma Valencia                      16.9%  ████████
    NS/NR                                 8.2%  ████

  [sv_cepeda_vs_pinzon]
    Iván Cepeda                          43.3%  █████████████████████
    Juan Carlos Pinzón                   17.0%  ████████
    No votaría                           16.3%  ████████
    Voto en blanco                       14.4%  ███████
    NS/NR                                 8.9%  ████

  [sv_fajardo_vs_pinzon]
    Sergio Fajardo                       29.1%  ██████████████
    Voto en blanco                       26.6%  █████████████
    No votaría                           24.4%  ████████████
    Juan Carlos Pinzón                   10.5%  █████
    NS/NR                                 9.4%  ████

==========================================================
  GAD3  |  2026-02-16  (n=2,473)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          33.9%  ████████████████
    Abelardo de la Espriella             26.3%  █████████████
    NS/NR                                13.0%  ██████
    Voto en blanco                        6.3%  ███
    Paloma Valencia                       3.7%  █
    Claudia López                         3.0%  █
    Vicky Dávila                          2.3%  █
    Sergio Fajardo                        2.3%  █
    Santiago Botero                       2.1%  █
    Otro                                  1.8%
    Juan Manuel Galán                     0.9%
    Juan Carlos Pinzón                    0.8%
    Roy Barreras                          0.7%
    Enrique Peñalosa                      0.7%
    Aníbal Gaviria                        0.4%
    Mauricio Cárdenas                     0.3%
    Juan Daniel Oviedo                    0.2%
    David Luna                            0.2%
    Germán Vargas Lleras                  0.2%
    Efraín Cepeda                         0.2%
    Luis Carlos Reyes                     0.1%
    Mauricio Lizcano                      0.1%
    Carlos Caicedo                        0.1%
    Felipe Córdoba                        0.1%
    Maurice Armitage                      0.1%
    Camilo Romero                         0.0%
    Paola Holguín                         0.0%

  [primera_vuelta_espontanea]
    Iván Cepeda                          33.9%  ████████████████
    Abelardo de la Espriella             26.3%  █████████████
    NS/NR                                13.0%  ██████
    Voto en blanco                        6.3%  ███
    Paloma Valencia                       3.7%  █
    Claudia López                         3.0%  █
    Vicky Dávila                          2.3%  █
    Sergio Fajardo                        2.3%  █
    Santiago Botero                       2.1%  █
    Otro                                  1.8%
    Juan Manuel Galán                     0.9%
    Juan Carlos Pinzón                    0.8%
    Roy Barreras                          0.7%
    Enrique Peñalosa                      0.7%
    Aníbal Gaviria                        0.4%
    Mauricio Cárdenas                     0.3%
    Juan Daniel Oviedo                    0.2%
    David Luna                            0.2%
    Germán Vargas Lleras                  0.2%
    Efraín Cepeda                         0.2%
    Luis Carlos Reyes                     0.1%
    Mauricio Lizcano                      0.1%
    Carlos Caicedo                        0.1%
    Felipe Córdoba                        0.1%
    Maurice Armitage                      0.1%
    Camilo Romero                         0.0%
    Paola Holguín                         0.0%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          38.1%  ███████████████████
    Abelardo de la Espriella             33.4%  ████████████████
    Voto en blanco                       14.0%  ███████
    No votaría                           10.5%  █████
    NS/NR                                 4.0%  ██

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          36.3%  ██████████████████
    Sergio Fajardo                       26.3%  █████████████
    No votaría                           16.9%  ████████
    Voto en blanco                       16.5%  ████████
    NS/NR                                 4.1%  ██

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          40.3%  ████████████████████
    Paloma Valencia                      25.3%  ████████████
    Voto en blanco                       15.4%  ███████
    No votaría                           15.3%  ███████
    NS/NR                                 3.6%  █

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             31.5%  ███████████████
    Voto en blanco                       22.3%  ███████████
    No votaría                           21.8%  ██████████
    Sergio Fajardo                       20.4%  ██████████
    NS/NR                                 4.1%  ██

  [sv_espriella_vs_valencia]
    Abelardo de la Espriella             34.2%  █████████████████
    Voto en blanco                       24.5%  ████████████
    No votaría                           24.1%  ████████████
    Paloma Valencia                      12.7%  ██████
    NS/NR                                 4.5%  ██

==========================================================
  GAD3  |  2026-03-16  (n=1,200)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          35.2%  █████████████████
    Abelardo de la Espriella             20.6%  ██████████
    Paloma Valencia                      15.6%  ███████
    NS/NR                                 6.7%  ███
    Voto en blanco                        6.2%  ███
    No votaría                            5.6%  ██
    Claudia López                         4.0%  ██
    Sergio Fajardo                        3.1%  █
    Miguel Uribe Londoño                  1.0%
    Santiago Botero                       0.8%
    Luis Gilberto Murillo                 0.5%
    Carlos Caicedo                        0.3%
    Clara López                           0.2%
    Mauricio Lizcano                      0.1%
    Roy Barreras                          0.1%

  [primera_vuelta_espontanea]
    Iván Cepeda                          35.2%  █████████████████
    Abelardo de la Espriella             20.6%  ██████████
    Paloma Valencia                      15.6%  ███████
    NS/NR                                 6.7%  ███
    Voto en blanco                        6.2%  ███
    No votaría                            5.6%  ██
    Claudia López                         4.0%  ██
    Sergio Fajardo                        3.1%  █
    Miguel Uribe Londoño                  1.0%
    Santiago Botero                       0.8%
    Luis Gilberto Murillo                 0.5%
    Carlos Caicedo                        0.3%
    Clara López                           0.2%
    Mauricio Lizcano                      0.1%
    Roy Barreras                          0.1%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          45.1%  ██████████████████████
    Abelardo de la Espriella             36.2%  ██████████████████
    Voto en blanco                       10.2%  █████
    No votaría                            6.4%  ███
    NS/NR                                 2.0%  █

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          44.5%  ██████████████████████
    Sergio Fajardo                       31.6%  ███████████████
    Voto en blanco                       12.0%  ██████
    No votaría                            9.5%  ████
    NS/NR                                 2.5%  █

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          43.0%  █████████████████████
    Paloma Valencia                      40.2%  ████████████████████
    Voto en blanco                        8.3%  ████
    No votaría                            6.3%  ███
    NS/NR                                 2.3%  █

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             32.5%  ████████████████
    Sergio Fajardo                       25.4%  ████████████
    Voto en blanco                       20.5%  ██████████
    No votaría                           18.6%  █████████
    NS/NR                                 3.0%  █

  [sv_espriella_vs_valencia]
    Abelardo de la Espriella             27.4%  █████████████
    Paloma Valencia                      27.3%  █████████████
    Voto en blanco                       23.3%  ███████████
    No votaría                           19.3%  █████████
    NS/NR                                 2.8%  █

In [10]:
# Invamer — Colombia Opina 21
revisar('Invamer')

==========================================================
  Invamer  |  2026-02-25  (n=3,801)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          33.3%  ████████████████
    Ninguno                              19.2%  █████████
    Abelardo de la Espriella             17.0%  ████████
    Claudia López                        11.3%  █████
    Sergio Fajardo                        8.2%  ████
    Paloma Valencia                       7.6%  ███
    Voto en blanco                        1.7%
    Roy Barreras                          1.5%
    P245                                  0.0%

  [primera_vuelta_espontanea]
    Iván Cepeda                          33.4%  ████████████████
    Ninguno                              18.6%  █████████
    Abelardo de la Espriella             17.8%  ████████
    Claudia López                        12.1%  ██████
    Sergio Fajardo                        8.8%  ████
    Paloma Valencia                       6.5%  ███
    Voto en blanco                        1.6%
    6                                     1.2%
    P247                                  0.0%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          45.9%  ██████████████████████
    Abelardo de la Espriella             28.4%  ██████████████
    Ninguno                              23.1%  ███████████
    Voto en blanco                        2.6%  █
    P233                                  0.0%

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          38.3%  ███████████████████
    Sergio Fajardo                       32.0%  ████████████████
    Ninguno                              27.2%  █████████████
    Voto en blanco                        2.6%  █
    P232                                  0.0%

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          47.6%  ███████████████████████
    Ninguno                              27.3%  █████████████
    Paloma Valencia                      22.0%  ███████████
    Voto en blanco                        3.1%  █
    P256                                  0.0%

  [sv_espriella_vs_fajardo]
    Ninguno                              40.9%  ████████████████████
    Sergio Fajardo                       28.9%  ██████████████
    Abelardo de la Espriella             26.5%  █████████████
    Voto en blanco                        3.7%  █
    P231                                  0.0%

  [aprobacion_petro]
    Aprueba                              49.1%  ████████████████████████
    Desaprueba                           46.1%  ███████████████████████
    NS/NR                                 4.7%  ██
    P2                                    0.0%

==========================================================
  Invamer  |  2026-04-25  (n=3,801)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          35.3%  █████████████████
    Abelardo de la Espriella             17.2%  ████████
    Paloma Valencia                      16.4%  ████████
    Ninguno                              15.1%  ███████
    Voto en blanco                        6.0%  ███
    Claudia López                         3.9%  █
    Sergio Fajardo                        2.5%  █
    Santiago Botero                       1.4%
    Carlos Caicedo                        0.5%
    Mauricio Lizcano                      0.4%
    Sondra Macollins                      0.4%
    Luis Gilberto Murillo                 0.3%
    Miguel Uribe Londoño                  0.3%
    Roy Barreras                          0.2%
    Gustavo Matamoros                     0.1%
    P245                                  0.0%

  [primera_vuelta_espontanea]
    Iván Cepeda                          37.3%  ██████████████████
    Abelardo de la Espriella             19.6%  █████████
    Paloma Valencia                      18.3%  █████████
    Ninguno                              12.3%  ██████
    Claudia López                         6.0%  ███
    Sergio Fajardo                        4.4%  ██
    Voto en blanco                        2.0%  █
    P247                                  0.0%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          46.9%  ███████████████████████
    Abelardo de la Espriella             35.9%  █████████████████
    Ninguno                              14.5%  ███████
    Voto en blanco                        2.7%  █
    P233                                  0.0%

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          48.1%  ████████████████████████
    Sergio Fajardo                       28.7%  ██████████████
    Ninguno                              20.1%  ██████████
    Voto en blanco                        3.1%  █
    P232                                  0.0%

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          44.6%  ██████████████████████
    Paloma Valencia                      40.9%  ████████████████████
    Ninguno                              12.3%  ██████
    Voto en blanco                        2.1%  █
    P256                                  0.0%

  [sv_espriella_vs_fajardo]
    Abelardo de la Espriella             36.8%  ██████████████████
    Ninguno                              32.3%  ████████████████
    Sergio Fajardo                       25.9%  ████████████
    Voto en blanco                        4.9%  ██
    P267                                  0.0%

  [sv_fajardo_vs_valencia]
    Paloma Valencia                      42.2%  █████████████████████
    Ninguno                              29.2%  ██████████████
    Sergio Fajardo                       23.7%  ███████████
    Voto en blanco                        4.9%  ██
    P268                                  0.0%

  [sv_cepeda_vs_claudia]
    Iván Cepeda                          47.4%  ███████████████████████
    Claudia López                        24.4%  ████████████
    Ninguno                              23.9%  ███████████
    Voto en blanco                        4.3%  ██
    P258                                  0.0%

  [aprobacion_petro]
    Desaprueba                           48.9%  ████████████████████████
    Aprueba                              47.3%  ███████████████████████
    NS/NR                                 3.8%  █
    P2                                    0.0%

In [11]:
# CNC — Febrero
revisar('CNC')

==========================================================
  CNC  |  2026-02-20  (n=3,684)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          35.4%  █████████████████
    Abelardo de la Espriella             16.7%  ████████
    NS/NR                                 8.8%  ████
    Ninguno                               6.3%  ███
    Claudia López                         5.2%  ██
    Sergio Fajardo                        4.8%  ██
    Paloma Valencia                       4.1%  ██
    Juan Manuel Galán                     2.6%  █
    Vicky Dávila                          2.0%  █
    Juan Daniel Oviedo                    1.8%
    Santiago Botero                       1.7%
    Daniel Quintero                       1.5%
    Voto en blanco                        1.2%
    Enrique Peñalosa                      1.2%
    Carlos Caicedo                        1.2%
    Miguel Uribe Londoño                  1.0%
    Juan Carlos Pinzón                    1.0%
    Roy Barreras                          0.9%
    Aníbal Gaviria                        0.7%
    Sondra Macollins                      0.7%
    David Luna                            0.5%
    Mauricio Cárdenas                     0.4%
    Luis Gilberto Murillo                 0.2%
    Mauricio Lizcano                      0.1%
    Maurice Armitage                      0.1%
    Juan Fernando Cristo                  0.0%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          55.0%  ███████████████████████████
    Abelardo de la Espriella             29.7%  ██████████████
    Ninguno                              10.4%  █████
    NS/NR                                 4.9%  ██

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          52.1%  ██████████████████████████
    Sergio Fajardo                       29.9%  ██████████████
    Ninguno                              13.0%  ██████
    NS/NR                                 5.1%  ██

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          57.0%  ████████████████████████████
    Paloma Valencia                      25.4%  ████████████
    Ninguno                              13.2%  ██████
    NS/NR                                 4.4%  ██

  [sv_cepeda_vs_claudia]
    Iván Cepeda                          51.3%  █████████████████████████
    Claudia López                        25.0%  ████████████
    Ninguno                              19.7%  █████████
    NS/NR                                 4.1%  ██

  [sv_cepeda_vs_davila]
    Iván Cepeda                          56.6%  ████████████████████████████
    Vicky Dávila                         23.3%  ███████████
    Ninguno                              16.4%  ████████
    NS/NR                                 3.7%  █

  [sv_cepeda_vs_galan]
    Iván Cepeda                          54.6%  ███████████████████████████
    Juan Manuel Galán                    26.8%  █████████████
    Ninguno                              14.1%  ███████
    NS/NR                                 4.6%  ██

  [sv_cepeda_vs_gaviria]
    Iván Cepeda                          57.1%  ████████████████████████████
    Aníbal Gaviria                       19.6%  █████████
    Ninguno                              18.1%  █████████
    NS/NR                                 5.1%  ██

  [sv_cardenas_vs_cepeda]
    Iván Cepeda                          58.1%  █████████████████████████████
    Ninguno                              21.3%  ██████████
    Mauricio Cárdenas                    15.7%  ███████
    NS/NR                                 4.9%  ██

  [aprobacion_petro]
    Positiva                             54.5%  ███████████████████████████
    Negativa                             38.4%  ███████████████████
    NS/NR                                 7.1%  ███

==========================================================
  CNC  |  2026-03-16  (n=2,157)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          34.5%  █████████████████
    Paloma Valencia                      22.2%  ███████████
    Abelardo de la Espriella             15.5%  ███████
    NS/NR                                 8.0%  ████
    Voto en blanco                        6.5%  ███
    Claudia López                         3.7%  █
    Sergio Fajardo                        3.6%  █
    Ninguno                               1.9%
    Santiago Botero                       1.3%
    Miguel Uribe Londoño                  1.0%
    Roy Barreras                          0.5%
    Sondra Macollins                      0.4%
    Clara López                           0.3%
    Gustavo Matamoros                     0.2%
    Luis Gilberto Murillo                 0.2%
    Mauricio Lizcano                      0.2%
    Carlos Caicedo                        0.1%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          48.0%  ████████████████████████
    Abelardo de la Espriella             35.5%  █████████████████
    Ninguno                              11.1%  █████
    NS/NR                                 5.3%  ██

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          47.3%  ███████████████████████
    Sergio Fajardo                       31.6%  ███████████████
    Ninguno                              15.8%  ███████
    NS/NR                                 5.4%  ██

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          43.3%  █████████████████████
    Paloma Valencia                      42.9%  █████████████████████
    Ninguno                               9.4%  ████
    NS/NR                                 4.4%  ██

  [sv_cepeda_vs_claudia]
    Iván Cepeda                          47.3%  ███████████████████████
    Claudia López                        26.6%  █████████████
    Ninguno                              21.8%  ██████████
    NS/NR                                 4.2%  ██

  [sv_barreras_vs_cepeda]
    Iván Cepeda                          54.0%  ███████████████████████████
    Ninguno                              28.7%  ██████████████
    Roy Barreras                         11.3%  █████
    NS/NR                                 6.0%  ███

  [sv_cepeda_vs_lizcano]
    Iván Cepeda                          52.9%  ██████████████████████████
    Ninguno                              24.9%  ████████████
    Mauricio Lizcano                     16.2%  ████████
    NS/NR                                 6.0%  ███

  [sv_cepeda_vs_murillo]
    Iván Cepeda                          53.7%  ██████████████████████████
    Ninguno                              26.9%  █████████████
    Luis Gilberto Murillo                13.8%  ██████
    NS/NR                                 5.7%  ██

  [sv_cepeda_vs_uribe_londono]
    Iván Cepeda                          50.1%  █████████████████████████
    Miguel Uribe Londoño                 26.0%  █████████████
    Ninguno                              19.0%  █████████
    NS/NR                                 4.9%  ██

  [aprobacion_petro]
    Positiva                             50.9%  █████████████████████████
    Negativa                             43.9%  █████████████████████
    NS/NR                                 5.2%  ██

In [12]:
# CNC — Marzo
revisar('CNC', '2026-03-16')

==========================================================
  CNC  |  2026-03-16  (n=2,157)
==========================================================

  [primera_vuelta]
    Iván Cepeda                          34.5%  █████████████████
    Paloma Valencia                      22.2%  ███████████
    Abelardo de la Espriella             15.5%  ███████
    NS/NR                                 8.0%  ████
    Voto en blanco                        6.5%  ███
    Claudia López                         3.7%  █
    Sergio Fajardo                        3.6%  █
    Ninguno                               1.9%
    Santiago Botero                       1.3%
    Miguel Uribe Londoño                  1.0%
    Roy Barreras                          0.5%
    Sondra Macollins                      0.4%
    Clara López                           0.3%
    Gustavo Matamoros                     0.2%
    Luis Gilberto Murillo                 0.2%
    Mauricio Lizcano                      0.2%
    Carlos Caicedo                        0.1%

  [sv_cepeda_vs_espriella]
    Iván Cepeda                          48.0%  ████████████████████████
    Abelardo de la Espriella             35.5%  █████████████████
    Ninguno                              11.1%  █████
    NS/NR                                 5.3%  ██

  [sv_cepeda_vs_fajardo]
    Iván Cepeda                          47.3%  ███████████████████████
    Sergio Fajardo                       31.6%  ███████████████
    Ninguno                              15.8%  ███████
    NS/NR                                 5.4%  ██

  [sv_cepeda_vs_valencia]
    Iván Cepeda                          43.3%  █████████████████████
    Paloma Valencia                      42.9%  █████████████████████
    Ninguno                               9.4%  ████
    NS/NR                                 4.4%  ██

  [sv_cepeda_vs_claudia]
    Iván Cepeda                          47.3%  ███████████████████████
    Claudia López                        26.6%  █████████████
    Ninguno                              21.8%  ██████████
    NS/NR                                 4.2%  ██

  [sv_barreras_vs_cepeda]
    Iván Cepeda                          54.0%  ███████████████████████████
    Ninguno                              28.7%  ██████████████
    Roy Barreras                         11.3%  █████
    NS/NR                                 6.0%  ███

  [sv_cepeda_vs_lizcano]
    Iván Cepeda                          52.9%  ██████████████████████████
    Ninguno                              24.9%  ████████████
    Mauricio Lizcano                     16.2%  ████████
    NS/NR                                 6.0%  ███

  [sv_cepeda_vs_murillo]
    Iván Cepeda                          53.7%  ██████████████████████████
    Ninguno                              26.9%  █████████████
    Luis Gilberto Murillo                13.8%  ██████
    NS/NR                                 5.7%  ██

  [sv_cepeda_vs_uribe_londono]
    Iván Cepeda                          50.1%  █████████████████████████
    Miguel Uribe Londoño                 26.0%  █████████████
    Ninguno                              19.0%  █████████
    NS/NR                                 4.9%  ██

  [aprobacion_petro]
    Positiva                             50.9%  █████████████████████████
    Negativa                             43.9%  █████████████████████
    NS/NR                                 5.2%  ██

## Trasbase — transferencia de votos primera vuelta → segunda vuelta

In [13]:

SV_COLS = [c for c in df.columns if c.startswith('sv_')]

def trasbase(encuestadora, fecha=None):
    """
    Para cada escenario de segunda vuelta muestra, entre quienes votan por
    cada candidato en primera vuelta, cómo se distribuye el voto (ponderado).
    """
    mask = df['encuestadora'] == encuestadora
    if fecha:
        mask &= df['fecha'].astype(str).str.startswith(str(fecha)[:10])
    sub = df[mask]

    for f, grupo in sub.groupby('fecha'):
        f_str = str(f)[:10]
        print(f"\n{'='*65}")
        print(f"  TRASBASE  |  {encuestadora}  |  {f_str}  (n={len(grupo):,})")
        print(f"{'='*65}")

        for sv_col in SV_COLS:
            validos = grupo[grupo[sv_col].notna() & grupo['primera_vuelta'].notna()].copy()
            if validos.empty:
                continue

            # Candidatos del escenario sv (excluir NS/NR, blancos, etc.)
            opciones = validos[sv_col].value_counts()
            candidatos_sv = [v for v in opciones.index]
            if len(candidatos_sv) < 2:
                continue

            print(f"\n  [{sv_col}]")

            # Tabla: filas = primera_vuelta, columnas = voto en sv
            ct = (validos
                  .groupby(['primera_vuelta', sv_col])['factor']
                  .sum()
                  .unstack(fill_value=0))

            # Ordenar columnas: candidatos primero, luego el resto
            col_order = candidatos_sv + [c for c in ct.columns if c not in candidatos_sv]
            ct = ct[[c for c in col_order if c in ct.columns]]

            # Normalizar por fila (% dentro de cada candidato de primera vuelta)
            ct_pct = ct.div(ct.sum(axis=1), axis=0) * 100

            # Ordenar filas por peso total descendente
            totales = validos.groupby('primera_vuelta')['factor'].sum().sort_values(ascending=False)
            filas_orden = [f for f in totales.index if f in ct_pct.index]
            ct_pct = ct_pct.loc[filas_orden]

            # Header
            col_labels = [str(c)[:18] for c in ct_pct.columns]
            header = f"    {'Primera vuelta':<28}" + "".join(f"{l:>10}" for l in col_labels)
            print(header)
            print("    " + "-" * (28 + 10 * len(col_labels)))

            for candidato_1v, row in ct_pct.iterrows():
                n_pond = int(totales.get(candidato_1v, 0))
                label = str(candidato_1v)[:26]
                vals = "".join(f"{v:>9.1f}%" for v in row.values)
                print(f"    {label:<28}{vals}  (n~{n_pond:,})")

In [14]:
trasbase('Atlas Intel')

=================================================================
  TRASBASE  |  Atlas Intel  |  2026-01-09  (n=4,520)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la EspVoto en blanco     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          0.2%     98.5%      1.1%      0.2%  (n~0)
    Iván Cepeda                      98.1%      0.4%      1.4%      0.2%  (n~0)
    Sergio Fajardo                   34.3%     29.2%     21.8%     14.7%  (n~0)
    Voto en blanco                    7.8%      4.1%     45.5%     42.6%  (n~0)
    No sé                             4.4%     11.3%     10.1%     74.2%  (n~0)
    Juan Carlos Pinzón               25.1%     63.6%     10.9%      0.5%  (n~0)
    Paloma Valencia                  16.3%     76.6%      7.0%      0.0%  (n~0)
    Claudia López                    27.1%     39.3%     28.1%      5.4%  (n~0)
    Enrique Peñalosa                 34.6%     29.5%      0.3%     35.5%  (n~0)
    Juan Daniel Oviedo               17.5%     27.0%     43.8%     11.7%  (n~0)
    Aníbal Gaviria                   31.6%     53.2%     14.8%      0.3%  (n~0)
    No votaría                        6.3%     23.7%     69.7%      0.4%  (n~0)
    Juan Manuel Galán                 5.4%     53.1%     41.6%      0.0%  (n~0)
    Vicky Dávila                      1.0%     76.7%      4.7%     17.6%  (n~0)
    David Luna                        0.0%     94.1%      0.2%      5.7%  (n~0)
    Daniel Quintero                  45.7%      0.0%     11.0%     43.4%  (n~0)
    Mauricio Cárdenas                 0.8%     80.9%     18.3%      0.0%  (n~0)
    Roy Barreras                     84.6%     14.9%      0.0%      0.5%  (n~0)
    Daniel Palacios                   0.0%    100.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio FajardoVoto en blanco     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          4.7%     55.8%     35.3%      4.2%  (n~0)
    Iván Cepeda                      98.9%      0.6%      0.4%      0.1%  (n~0)
    Sergio Fajardo                    0.0%     96.9%      0.0%      3.0%  (n~0)
    Voto en blanco                    7.5%      6.9%     41.8%     43.8%  (n~0)
    No sé                             3.6%     11.6%      9.9%     74.9%  (n~0)
    Juan Carlos Pinzón                8.9%     71.4%     19.7%      0.0%  (n~0)
    Paloma Valencia                  16.3%     70.5%     13.1%      0.1%  (n~0)
    Claudia López                    21.2%     67.0%      7.5%      4.3%  (n~0)
    Enrique Peñalosa                 33.8%     31.1%      0.0%     35.2%  (n~0)
    Juan Daniel Oviedo               11.7%     73.6%     14.7%      0.0%  (n~0)
    Aníbal Gaviria                    0.2%     64.1%      4.3%     31.4%  (n~0)
    No votaría                        6.3%      0.1%     93.0%      0.5%  (n~0)
    Juan Manuel Galán                42.1%     21.3%     36.6%      0.0%  (n~0)
    Vicky Dávila                      1.0%     68.5%     12.7%     17.8%  (n~0)
    David Luna                       11.9%     30.1%     52.2%      5.7%  (n~0)
    Daniel Quintero                  42.8%     53.1%      4.1%      0.0%  (n~0)
    Mauricio Cárdenas                 0.8%     81.0%     18.2%      0.0%  (n~0)
    Roy Barreras                     82.5%     17.5%      0.0%      0.0%  (n~0)
    Daniel Palacios                   0.0%    100.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_pinzon]
    Primera vuelta              Iván CepedaJuan Carlos PinzónVoto en blanco     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          4.7%     56.4%     34.2%      4.7%  (n~0)
    Iván Cepeda                      99.3%      0.5%      0.1%      0.0%  (n~0)
    Sergio Fajardo                   31.1%     40.1%     14.0%     14.7%  (n~0)
    Voto en blanco                    9.6%      3.9%     56.3%     30.1%  (n~0)
    No sé                             4.4%     10.7%     10.2%     74.8%  (n~0)
    Juan Carlos Pinzón                8.9%     82.6%      8.6%      0.0%  (n~0)
    Paloma Valencia                  16.3%     56.1%     26.5%      1.1%  (n~0)
    Claudia López                    27.7%     53.4%     14.1%      4.8%  (n~0)
    Enrique Peñalosa                 34.7%     29.6%      0.5%     35.2%  (n~0)
    Juan Daniel Oviedo               16.9%     27.1%     43.1%     12.9%  (n~0)
    Aníbal Gaviria                   31.6%     29.9%      2.0%     36.5%  (n~0)
    No votaría                        6.3%      0.1%     93.2%      0.4%  (n~0)
    Juan Manuel Galán                47.2%     10.5%     42.3%      0.0%  (n~0)
    Vicky Dávila                      1.0%     49.8%     12.4%     36.8%  (n~0)
    David Luna                       41.6%     29.6%     23.1%      5.7%  (n~0)
    Daniel Quintero                  47.7%      0.0%      8.9%     43.4%  (n~0)
    Mauricio Cárdenas                 7.6%     92.2%      0.2%      0.0%  (n~0)
    Roy Barreras                     82.9%     16.6%      0.0%      0.5%  (n~0)
    Daniel Palacios                   0.0%    100.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván CepedaPaloma ValenciaVoto en blanco     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          5.5%     71.7%     18.5%      4.3%  (n~0)
    Iván Cepeda                      98.6%      0.4%      1.0%      0.0%  (n~0)
    Sergio Fajardo                   31.8%     39.9%     14.3%     14.0%  (n~0)
    Voto en blanco                    8.3%      2.6%     42.5%     46.6%  (n~0)
    No sé                             4.4%     17.8%      3.5%     74.3%  (n~0)
    Juan Carlos Pinzón                8.8%     73.1%     18.1%      0.0%  (n~0)
    Paloma Valencia                  16.3%     83.7%      0.0%      0.0%  (n~0)
    Claudia López                    23.5%     56.3%     14.7%      5.5%  (n~0)
    Enrique Peñalosa                 34.6%     29.0%      1.2%     35.2%  (n~0)
    Juan Daniel Oviedo               19.0%     22.5%     46.1%     12.3%  (n~0)
    Aníbal Gaviria                   31.6%     27.9%      4.3%     36.2%  (n~0)
    No votaría                        6.3%      6.9%     86.4%      0.4%  (n~0)
    Juan Manuel Galán                 5.4%     52.7%     41.9%      0.0%  (n~0)
    Vicky Dávila                      1.0%     69.1%     12.3%     17.6%  (n~0)
    David Luna                       41.6%     52.6%      0.1%      5.7%  (n~0)
    Daniel Quintero                  47.7%      0.0%      8.9%     43.4%  (n~0)
    Mauricio Cárdenas                 0.9%     80.9%     18.2%      0.0%  (n~0)
    Roy Barreras                     84.6%     14.9%      0.0%      0.5%  (n~0)
    Daniel Palacios                   0.0%    100.0%      0.0%      0.0%  (n~0)

  [sv_espriella_vs_fajardo]
    Primera vuelta              Voto en blancoAbelardo de la EspSergio Fajardo     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          0.7%     96.3%      2.2%      0.8%  (n~0)
    Iván Cepeda                      75.1%      0.8%     18.3%      5.8%  (n~0)
    Sergio Fajardo                    0.3%      2.2%     94.6%      3.0%  (n~0)
    Voto en blanco                   49.0%      0.3%      5.7%     45.1%  (n~0)
    No sé                            10.0%     10.9%      1.2%     77.9%  (n~0)
    Juan Carlos Pinzón                8.4%     53.9%     37.5%      0.2%  (n~0)
    Paloma Valencia                   1.6%     57.8%     40.6%      0.0%  (n~0)
    Claudia López                     7.0%     39.3%     30.4%     23.3%  (n~0)
    Enrique Peñalosa                 27.7%     19.8%     17.0%     35.5%  (n~0)
    Juan Daniel Oviedo               18.9%      8.0%     60.4%     12.7%  (n~0)
    Aníbal Gaviria                    3.4%     40.3%     56.3%      0.0%  (n~0)
    No votaría                       68.8%     23.6%      6.9%      0.7%  (n~0)
    Juan Manuel Galán                36.8%     42.8%     20.4%      0.0%  (n~0)
    Vicky Dávila                      6.3%     75.8%      0.3%     17.6%  (n~0)
    David Luna                        0.2%     43.4%     50.6%      5.7%  (n~0)
    Daniel Quintero                  12.9%      0.0%     87.1%      0.0%  (n~0)
    Mauricio Cárdenas                18.1%     48.2%     33.6%      0.1%  (n~0)
    Roy Barreras                     14.6%     14.9%     70.5%      0.0%  (n~0)
    Daniel Palacios                   0.0%      0.0%    100.0%      0.0%  (n~0)

=================================================================
  TRASBASE  |  Atlas Intel  |  2026-02-05  (n=7,298)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la EspVoto en blanco     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          1.5%     96.5%      0.2%      1.8%  (n~0)
    Iván Cepeda                      99.5%      0.1%      0.3%      0.1%  (n~0)
    No sé                            11.4%     15.4%     17.3%     55.9%  (n~0)
    Sergio Fajardo                    9.9%     20.6%     42.0%     27.5%  (n~0)
    Blanco                           15.1%      5.7%     66.7%     12.5%  (n~0)
    Voto en blanco                    8.1%     13.7%     71.6%      6.6%  (n~0)
    Paloma Valencia                   5.9%     40.1%     36.0%     17.9%  (n~0)
    Claudia López                    43.3%      7.7%     17.6%     31.3%  (n~0)
    Miguel Uribe Londoño             13.1%     48.6%     20.0%     18.3%  (n~0)
    Vicky Dávila                      6.1%     40.5%     30.8%     22.6%  (n~0)
    Juan Carlos Pinzón               12.1%     35.1%     39.3%     13.5%  (n~0)
    Juan Daniel Oviedo               12.2%     31.1%     44.3%     12.4%  (n~0)
    Daniel Quintero                  36.8%      5.2%     32.7%     25.3%  (n~0)
    Juan Manuel Galán                 2.5%     44.1%     35.8%     17.6%  (n~0)
    Enrique Peñalosa                 11.6%     31.6%     28.6%     28.2%  (n~0)
    Aníbal Gaviria                    7.0%     27.0%     42.5%     23.4%  (n~0)
    Santiago Botero                  28.7%     21.5%     41.1%      8.6%  (n~0)
    David Luna                       22.7%     40.2%     37.0%      0.1%  (n~0)
    Camilo Romero                    52.2%      1.3%     41.1%      5.4%  (n~0)
    Roy Barreras                      7.9%     12.6%     11.1%     68.4%  (n~0)
    Daniel Palacios                  10.6%     11.1%     42.2%     36.1%  (n~0)
    Mauricio Cárdenas                 1.5%     12.2%     85.7%      0.5%  (n~0)
    Juan Fernando Cristo              0.0%      9.0%      4.9%     86.1%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaVoto en blancoSergio Fajardo     No sé
    --------------------------------------------------------------------
    Abelardo de la Espriella          2.7%     41.1%     40.5%     15.7%  (n~0)
    Iván Cepeda                      98.1%      0.3%      0.6%      0.9%  (n~0)
    No sé                            11.3%     15.5%     16.4%     56.8%  (n~0)
    Sergio Fajardo                    4.4%      2.1%     91.4%      2.1%  (n~0)
    Blanco                           12.7%     63.1%     11.1%     13.1%  (n~0)
    Voto en blanco                    5.1%     79.6%      8.7%      6.6%  (n~0)
    Paloma Valencia                   6.0%     51.5%     21.2%     21.3%  (n~0)
    Claudia López                    37.0%     17.6%     16.7%     28.7%  (n~0)
    Miguel Uribe Londoño             14.2%     52.0%     25.5%      8.2%  (n~0)
    Vicky Dávila                      7.3%     28.2%     43.7%     20.8%  (n~0)
    Juan Carlos Pinzón                7.5%     52.4%     25.5%     14.6%  (n~0)
    Juan Daniel Oviedo                8.3%     15.7%     68.0%      7.9%  (n~0)
    Daniel Quintero                  28.0%     15.6%     24.5%     31.9%  (n~0)
    Juan Manuel Galán                 6.2%     47.8%     28.4%     17.6%  (n~0)
    Enrique Peñalosa                 14.4%     27.9%     30.2%     27.5%  (n~0)
    Aníbal Gaviria                    8.8%     30.4%     40.4%     20.3%  (n~0)
    Santiago Botero                  20.2%     59.5%     16.4%      3.9%  (n~0)
    David Luna                       20.3%     30.7%     47.7%      1.4%  (n~0)
    Camilo Romero                    77.8%      7.3%     14.3%      0.5%  (n~0)
    Roy Barreras                      6.9%      2.9%     62.4%     27.8%  (n~0)
    Daniel Palacios                  20.3%      7.4%     37.3%     35.0%  (n~0)
    Mauricio Cárdenas                 4.4%     41.4%     53.7%      0.5%  (n~0)
    Juan Fernando Cristo              0.0%      0.1%     23.2%     76.8%  (n~0)

  [sv_cepeda_vs_pinzon]
    Primera vuelta              Iván CepedaVoto en blanco     No séJuan Carlos Pinzón
    --------------------------------------------------------------------
    Abelardo de la Espriella          3.9%     41.2%     15.7%     39.2%  (n~0)
    Iván Cepeda                      99.0%      0.2%      0.7%      0.0%  (n~0)
    No sé                            12.6%     16.7%     62.2%      8.5%  (n~0)
    Sergio Fajardo                    9.3%     43.1%     27.5%     20.1%  (n~0)
    Blanco                           16.6%     65.8%     14.2%      3.4%  (n~0)
    Voto en blanco                   10.4%     77.9%      9.5%      2.2%  (n~0)
    Paloma Valencia                   6.1%     53.0%     18.8%     22.1%  (n~0)
    Claudia López                    45.0%     20.8%     32.7%      1.5%  (n~0)
    Miguel Uribe Londoño             16.6%     19.8%      8.4%     55.2%  (n~0)
    Vicky Dávila                     12.8%     28.3%     30.5%     28.4%  (n~0)
    Juan Carlos Pinzón                7.4%     15.0%     11.6%     66.0%  (n~0)
    Juan Daniel Oviedo               14.6%     45.4%     10.0%     30.0%  (n~0)
    Daniel Quintero                  39.0%     25.6%     28.6%      6.7%  (n~0)
    Juan Manuel Galán                 7.0%     45.7%     21.1%     26.3%  (n~0)
    Enrique Peñalosa                 14.9%     29.4%     25.2%     30.5%  (n~0)
    Aníbal Gaviria                   12.8%     54.4%     11.2%     21.6%  (n~0)
    Santiago Botero                  26.8%     46.8%      2.5%     23.9%  (n~0)
    David Luna                       20.3%     24.1%      1.3%     54.3%  (n~0)
    Camilo Romero                    70.0%     18.0%      6.2%      5.8%  (n~0)
    Roy Barreras                     12.4%      2.9%     70.7%     14.1%  (n~0)
    Daniel Palacios                  20.6%     42.2%     36.3%      0.9%  (n~0)
    Mauricio Cárdenas                 1.5%     95.1%      0.5%      2.9%  (n~0)
    Juan Fernando Cristo              0.0%      4.9%     86.1%      9.0%  (n~0)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván CepedaVoto en blanco     No séPaloma Valencia
    --------------------------------------------------------------------
    Abelardo de la Espriella          3.4%     32.3%     14.4%     50.0%  (n~0)
    Iván Cepeda                      99.5%      0.0%      0.4%      0.1%  (n~0)
    No sé                            11.2%     16.5%     55.9%     16.4%  (n~0)
    Sergio Fajardo                   11.1%     33.6%     19.5%     35.9%  (n~0)
    Blanco                           13.9%     62.4%     12.5%     11.2%  (n~0)
    Voto en blanco                    9.8%     73.4%     11.2%      5.6%  (n~0)
    Paloma Valencia                   3.7%      4.8%      4.5%     87.0%  (n~0)
    Claudia López                    31.2%     10.7%     31.1%     27.1%  (n~0)
    Miguel Uribe Londoño             16.3%     28.3%      4.8%     50.6%  (n~0)
    Vicky Dávila                      9.4%     21.4%     19.2%     50.1%  (n~0)
    Juan Carlos Pinzón               12.1%     48.2%      2.7%     37.0%  (n~0)
    Juan Daniel Oviedo               11.8%     46.8%      9.3%     32.2%  (n~0)
    Daniel Quintero                  35.1%     29.4%     28.8%      6.8%  (n~0)
    Juan Manuel Galán                 6.9%     41.5%     11.9%     39.6%  (n~0)
    Enrique Peñalosa                 11.6%     33.3%     27.7%     27.4%  (n~0)
    Aníbal Gaviria                   14.1%     47.6%     14.1%     24.3%  (n~0)
    Santiago Botero                  27.9%     46.6%      3.9%     21.7%  (n~0)
    David Luna                       25.1%     40.4%      1.4%     33.1%  (n~0)
    Camilo Romero                    76.0%     17.3%      5.4%      1.3%  (n~0)
    Roy Barreras                     15.5%     12.1%     49.7%     22.7%  (n~0)
    Daniel Palacios                  21.2%     42.2%     36.3%      0.3%  (n~0)
    Mauricio Cárdenas                 1.5%     95.1%      0.5%      2.9%  (n~0)
    Juan Fernando Cristo              0.0%     14.3%     76.8%      9.0%  (n~0)

  [sv_espriella_vs_fajardo]
    Primera vuelta              Voto en blanco     No séAbelardo de la EspSergio Fajardo
    --------------------------------------------------------------------
    Abelardo de la Espriella          2.9%      2.8%     90.4%      3.9%  (n~0)
    Iván Cepeda                      55.2%     22.7%      0.6%     21.5%  (n~0)
    No sé                            16.7%     59.6%     13.8%      9.9%  (n~0)
    Sergio Fajardo                    1.5%      2.7%      1.2%     94.6%  (n~0)
    Blanco                           65.5%     15.5%      7.2%     11.8%  (n~0)
    Voto en blanco                   75.7%      9.0%      3.2%     12.2%  (n~0)
    Paloma Valencia                  31.3%     17.7%     36.3%     14.7%  (n~0)
    Claudia López                    20.8%     46.1%      4.6%     28.6%  (n~0)
    Miguel Uribe Londoño             34.9%      8.2%     31.8%     25.0%  (n~0)
    Vicky Dávila                     27.1%     19.4%     26.8%     26.7%  (n~0)
    Juan Carlos Pinzón               37.1%      2.6%     22.1%     38.2%  (n~0)
    Juan Daniel Oviedo               15.5%      8.2%     26.6%     49.6%  (n~0)
    Daniel Quintero                  28.3%     38.3%      3.3%     30.1%  (n~0)
    Juan Manuel Galán                43.2%      5.9%     28.5%     22.4%  (n~0)
    Enrique Peñalosa                 26.9%     24.9%     16.4%     31.8%  (n~0)
    Aníbal Gaviria                   28.5%     17.6%     25.5%     28.4%  (n~0)
    Santiago Botero                  54.4%      7.0%     26.5%     12.1%  (n~0)
    David Luna                        4.6%     19.0%     18.8%     57.6%  (n~0)
    Camilo Romero                     5.2%      9.3%      0.9%     84.6%  (n~0)
    Roy Barreras                      6.3%     28.7%     12.6%     52.4%  (n~0)
    Daniel Palacios                  15.6%     34.7%     11.1%     38.5%  (n~0)
    Mauricio Cárdenas                45.1%      0.5%      0.0%     54.4%  (n~0)
    Juan Fernando Cristo              0.1%     76.8%      9.0%     14.2%  (n~0)

=================================================================
  TRASBASE  |  Atlas Intel  |  2026-02-28  (n=6,468)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la EspVoto en blanco     No sé
    --------------------------------------------------------------------
    Iván Cepeda                      98.9%      0.3%      0.6%      0.2%  (n~0)
    Abelardo de la Espriella          0.2%     99.1%      0.5%      0.1%  (n~0)
    Sergio Fajardo                   17.8%     35.0%     37.2%      9.9%  (n~0)
    Voto en blanco                    0.3%      2.2%     76.0%     21.6%  (n~0)
    Blanco                            2.1%     16.2%     77.5%      4.2%  (n~0)
    Paloma Valencia                   8.8%     51.1%     28.4%     11.8%  (n~0)
    No sé                            17.7%      7.9%     21.5%     53.0%  (n~0)

In [15]:
trasbase('GAD3')

=================================================================
  TRASBASE  |  GAD3  |  2026-01-13  (n=1,207)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la EspVoto en blancoNo votaría     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.3%      0.8%      0.5%      0.4%      0.0%  (n~365)
    Abelardo de la Espriella          1.4%     98.6%      0.0%      0.0%      0.0%  (n~264)
    NS/NR                            14.8%     17.3%     18.9%      6.9%     42.2%  (n~169)
    Ninguno                          14.2%      5.0%     14.7%     58.0%      8.1%  (n~128)
    Voto en blanco                   25.5%      4.9%     56.3%      9.4%      3.7%  (n~59)
    Paloma Valencia                  16.1%     80.4%      0.0%      3.6%      0.0%  (n~37)
    Juan Manuel Galán                19.6%     23.9%     19.6%     23.9%     12.9%  (n~25)
    Vicky Dávila                     44.0%     28.0%     28.1%      0.0%      0.0%  (n~21)
    Juan Carlos Pinzón                1.7%     70.0%     12.5%     12.6%      3.1%  (n~20)
    Sergio Fajardo                    1.8%     50.8%     43.8%      3.5%      0.0%  (n~15)
    Aníbal Gaviria                   29.6%     34.8%     34.3%      1.3%      0.0%  (n~13)
    Juan Daniel Oviedo               44.4%      5.9%     36.2%     13.5%      0.0%  (n~13)
    Otro                             57.1%     14.4%      5.6%     17.6%      5.2%  (n~12)
    Santiago Botero                  38.5%     27.0%      8.2%     26.4%      0.0%  (n~12)
    María Fernanda Cabal             20.0%     16.8%     59.1%      4.1%      0.0%  (n~10)
    Roy Barreras                     48.5%     34.2%      0.0%     17.3%      0.0%  (n~9)
    Camilo Romero                    80.5%      0.0%     11.3%      8.1%      0.0%  (n~8)
    Enrique Peñalosa                 20.5%     41.8%     37.7%      0.0%      0.0%  (n~6)
    Claudia López                    56.8%      0.0%     17.0%      1.1%     25.1%  (n~5)
    Germán Vargas Lleras             45.8%      0.0%     54.2%      0.0%      0.0%  (n~4)
    Mauricio Cárdenas                41.0%      0.0%      6.2%     52.9%      0.0%  (n~3)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio FajardoNo votaríaVoto en blanco     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      95.8%      2.7%      0.9%      0.4%      0.3%  (n~365)
    Abelardo de la Espriella          5.6%     49.8%     22.6%     21.5%      0.5%  (n~264)
    NS/NR                            12.7%     26.3%      9.5%      9.8%     41.7%  (n~169)
    Ninguno                          13.1%     12.8%     52.7%     12.5%      9.0%  (n~128)
    Voto en blanco                   25.9%     10.9%      8.4%     51.6%      3.3%  (n~59)
    Paloma Valencia                   7.6%     70.2%     13.9%      7.5%      0.7%  (n~37)
    Juan Manuel Galán                19.7%     52.7%     25.6%      2.0%      0.0%  (n~25)
    Vicky Dávila                     34.4%     42.9%      5.7%     17.0%      0.0%  (n~21)
    Juan Carlos Pinzón               13.3%     62.9%     18.3%      5.6%      0.0%  (n~20)
    Sergio Fajardo                    0.0%    100.0%      0.0%      0.0%      0.0%  (n~15)
    Aníbal Gaviria                   20.9%     16.0%     17.9%     45.2%      0.0%  (n~13)
    Juan Daniel Oviedo               38.0%     16.6%     18.0%     16.1%     11.4%  (n~13)
    Otro                             57.1%     14.4%     17.6%      5.6%      5.2%  (n~12)
    Santiago Botero                  43.9%     14.3%     15.1%     26.8%      0.0%  (n~12)
    María Fernanda Cabal             20.0%      4.1%     49.1%     26.8%      0.0%  (n~10)
    Roy Barreras                     62.3%     37.7%      0.0%      0.0%      0.0%  (n~9)
    Camilo Romero                    53.3%     20.8%      0.0%     25.9%      0.0%  (n~8)
    Enrique Peñalosa                 37.4%     41.8%     20.8%      0.0%      0.0%  (n~6)
    Claudia López                    56.8%     18.2%      0.0%      0.0%     25.1%  (n~5)
    Germán Vargas Lleras             45.8%     54.2%      0.0%      0.0%      0.0%  (n~4)
    Mauricio Cárdenas                 0.0%     26.3%     32.7%      0.0%     41.0%  (n~3)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_pinzon]
    Primera vuelta              Iván CepedaJuan Carlos PinzónNo votaríaVoto en blanco     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.8%      0.2%      0.1%      0.8%      0.1%  (n~365)
    Abelardo de la Espriella          7.5%     42.5%     24.7%     22.9%      2.3%  (n~264)
    NS/NR                            20.2%     12.9%     10.2%     10.9%     45.8%  (n~169)
    Ninguno                          12.7%      7.1%     54.6%     14.2%     11.4%  (n~128)
    Voto en blanco                   30.3%      0.7%     11.6%     54.2%      3.2%  (n~59)
    Paloma Valencia                  11.1%     55.0%     15.6%     18.3%      0.0%  (n~37)
    Juan Manuel Galán                22.3%     11.1%     29.1%     22.6%     14.9%  (n~25)
    Vicky Dávila                     60.3%      0.0%     22.7%     17.0%      0.0%  (n~21)
    Juan Carlos Pinzón               15.5%     84.5%      0.0%      0.0%      0.0%  (n~20)
    Sergio Fajardo                    5.5%     43.7%     13.0%     37.8%      0.0%  (n~15)
    Aníbal Gaviria                   34.2%     18.2%      1.3%     46.3%      0.0%  (n~13)
    Juan Daniel Oviedo               38.0%      8.4%     27.6%     14.6%     11.4%  (n~13)
    Otro                             57.1%     13.9%     18.5%      5.2%      5.2%  (n~12)
    Santiago Botero                  55.3%      2.8%     15.1%     26.8%      0.0%  (n~12)
    María Fernanda Cabal              1.4%     18.6%     34.7%     45.3%      0.0%  (n~10)
    Roy Barreras                     48.5%     24.4%     27.1%      0.0%      0.0%  (n~9)
    Camilo Romero                    80.5%      0.0%      0.0%     19.5%      0.0%  (n~8)
    Enrique Peñalosa                 37.4%     18.3%     23.5%     20.8%      0.0%  (n~6)
    Claudia López                    56.8%     17.0%      1.1%      0.0%     25.1%  (n~5)
    Germán Vargas Lleras            100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    Mauricio Cárdenas                41.0%     20.1%     32.7%      6.2%      0.0%  (n~3)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván CepedaPaloma ValenciaNo votaríaVoto en blanco     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.2%      0.0%      0.3%      1.5%      0.0%  (n~365)
    Abelardo de la Espriella          7.0%     53.8%     17.1%     20.0%      2.0%  (n~264)
    NS/NR                            19.7%     13.8%      9.3%     15.0%     42.3%  (n~169)
    Ninguno                          11.7%      9.3%     58.4%     11.6%      9.0%  (n~128)
    Voto en blanco                   28.3%      2.1%     18.1%     47.8%      3.6%  (n~59)
    Paloma Valencia                   9.0%     91.0%      0.0%      0.0%      0.0%  (n~37)
    Juan Manuel Galán                24.6%     15.5%     38.8%      8.1%     12.9%  (n~25)
    Vicky Dávila                     58.5%      6.2%     22.7%     12.5%      0.0%  (n~21)
    Juan Carlos Pinzón               31.1%     49.2%      6.4%     10.1%      3.1%  (n~20)
    Sergio Fajardo                    5.5%     37.4%      3.5%     47.9%      5.7%  (n~15)
    Aníbal Gaviria                   42.5%      1.6%     10.6%     45.2%      0.0%  (n~13)
    Juan Daniel Oviedo               38.5%      0.0%     27.6%     33.9%      0.0%  (n~13)
    Otro                             57.1%      8.6%     23.9%      5.2%      5.2%  (n~12)
    Santiago Botero                  55.3%      2.8%     15.1%     26.8%      0.0%  (n~12)
    María Fernanda Cabal             20.0%     20.9%      0.0%     59.1%      0.0%  (n~10)
    Roy Barreras                     44.4%     38.3%     17.3%      0.0%      0.0%  (n~9)
    Camilo Romero                    80.5%      0.0%      0.0%     19.5%      0.0%  (n~8)
    Enrique Peñalosa                 37.4%     12.8%     26.3%     23.5%      0.0%  (n~6)
    Claudia López                    56.8%     17.0%      1.1%      0.0%     25.1%  (n~5)
    Germán Vargas Lleras             45.8%      0.0%      0.0%     54.2%      0.0%  (n~4)
    Mauricio Cárdenas                41.0%      0.0%     32.7%      6.2%     20.1%  (n~3)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%      0.0%  (n~0)

  [sv_espriella_vs_fajardo]
    Primera vuelta              Abelardo de la EspNo votaríaVoto en blancoSergio Fajardo     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                       4.1%     32.2%     40.6%     19.7%      3.4%  (n~365)
    Abelardo de la Espriella         97.3%      0.0%      0.3%      2.4%      0.0%  (n~264)
    NS/NR                            15.6%     10.7%     12.0%     17.5%     44.2%  (n~169)
    Ninguno                          12.0%     46.4%     16.6%     14.8%     10.3%  (n~128)
    Voto en blanco                    5.0%     20.1%     56.9%     17.0%      1.0%  (n~59)
    Paloma Valencia                  63.1%      4.9%      9.1%     22.8%      0.0%  (n~37)
    Juan Manuel Galán                15.0%     29.5%      5.2%     48.3%      2.0%  (n~25)
    Vicky Dávila                     16.3%     15.7%     17.0%     43.3%      7.7%  (n~21)
    Juan Carlos Pinzón               57.7%      6.3%     10.3%     25.7%      0.0%  (n~20)
    Sergio Fajardo                    0.0%      0.0%      0.0%     94.3%      5.7%  (n~15)
    Aníbal Gaviria                   55.3%      0.0%     33.2%     11.5%      0.0%  (n~13)
    Juan Daniel Oviedo                5.9%     21.7%     26.8%     45.6%      0.0%  (n~13)
    Otro                             19.3%     26.5%      0.3%     43.5%     10.4%  (n~12)
    Santiago Botero                  24.7%     34.6%      0.0%     40.8%      0.0%  (n~12)
    María Fernanda Cabal             49.2%      0.0%     26.8%     23.1%      0.9%  (n~10)
    Roy Barreras                     19.9%     17.3%      0.0%     62.8%      0.0%  (n~9)
    Camilo Romero                    13.6%      7.6%     40.2%     38.6%      0.0%  (n~8)
    Enrique Peñalosa                 27.4%      0.0%     16.9%     55.6%      0.0%  (n~6)
    Claudia López                     0.0%      0.0%     25.6%     34.0%     40.4%  (n~5)
    Germán Vargas Lleras              0.0%      0.0%     92.3%      7.7%      0.0%  (n~4)
    Mauricio Cárdenas                 0.0%     32.7%      0.0%     67.3%      0.0%  (n~3)
    Mauricio Lizcano                  0.0%      0.0%      0.0%      0.0%    100.0%  (n~0)

  [sv_fajardo_vs_pinzon]
    Primera vuelta              Sergio FajardoNo votaríaVoto en blancoJuan Carlos Pinzón     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      21.9%     32.7%     41.2%      2.3%      1.9%  (n~365)
    Abelardo de la Espriella         37.7%     18.2%     18.0%     22.8%      3.4%  (n~264)
    NS/NR                            21.1%     10.0%     16.8%      7.9%     44.3%  (n~169)
    Ninguno                          16.2%     55.1%     14.8%      3.6%     10.3%  (n~128)
    Voto en blanco                   17.5%     15.2%     63.3%      0.4%      3.6%  (n~59)
    Paloma Valencia                  48.6%     12.9%     16.8%     21.7%      0.0%  (n~37)
    Juan Manuel Galán                55.9%     29.5%      5.3%      7.4%      2.0%  (n~25)
    Vicky Dávila                     53.2%     15.7%     17.0%      6.5%      7.7%  (n~21)
    Juan Carlos Pinzón               14.9%      0.0%      0.0%     85.1%      0.0%  (n~20)
    Sergio Fajardo                   94.2%      0.0%      0.0%      0.0%      5.8%  (n~15)
    Aníbal Gaviria                   11.5%      0.0%     45.2%     43.3%      0.0%  (n~13)
    Juan Daniel Oviedo               43.6%     21.7%     26.8%      7.9%      0.0%  (n~13)
    Otro                             62.8%     26.5%      0.3%      0.0%     10.4%  (n~12)
    Santiago Botero                  43.3%     32.8%     21.0%      2.8%      0.0%  (n~12)
    María Fernanda Cabal             36.9%      0.0%     43.7%     18.6%      0.9%  (n~10)
    Roy Barreras                     82.7%     17.3%      0.0%      0.0%      0.0%  (n~9)
    Camilo Romero                    38.6%      7.6%     40.2%     13.6%      0.0%  (n~8)
    Enrique Peñalosa                 77.5%      0.0%     16.9%      5.6%      0.0%  (n~6)
    Claudia López                    34.0%     25.6%      0.0%      0.0%     40.4%  (n~5)
    Germán Vargas Lleras              7.7%      0.0%     92.3%      0.0%      0.0%  (n~4)
    Mauricio Cárdenas                26.3%     32.7%     41.0%      0.0%      0.0%  (n~3)
    Mauricio Lizcano                  0.0%      0.0%      0.0%      0.0%    100.0%  (n~0)

  [sv_fajardo_vs_valencia]
    Primera vuelta              Sergio FajardoNo votaríaVoto en blancoPaloma Valencia     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      23.8%     29.3%     42.6%      2.5%      1.9%  (n~365)
    Abelardo de la Espriella         30.7%     12.9%     14.9%     38.8%      2.8%  (n~264)
    NS/NR                            21.2%     10.6%     14.7%     15.8%     37.7%  (n~169)
    Ninguno                          16.4%     55.4%     13.6%      5.6%      9.0%  (n~128)
    Voto en blanco                   20.5%     14.2%     59.3%      2.8%      3.2%  (n~59)
    Paloma Valencia                   8.5%      0.0%      0.0%     91.5%      0.0%  (n~37)
    Juan Manuel Galán                65.0%     18.7%      6.7%      7.6%      2.0%  (n~25)
    Vicky Dávila                     57.8%     15.7%     12.5%      6.2%      7.7%  (n~21)
    Juan Carlos Pinzón               36.1%     12.0%     10.1%     41.7%      0.0%  (n~20)
    Sergio Fajardo                   90.7%      0.0%      0.0%      9.3%      0.0%  (n~15)
    Aníbal Gaviria                   24.8%      9.4%     55.7%     10.1%      0.0%  (n~13)
    Juan Daniel Oviedo               51.6%     21.7%     26.8%      0.0%      0.0%  (n~13)
    Otro                             54.2%     26.5%      0.3%      8.6%     10.4%  (n~12)
    Santiago Botero                  46.2%     35.3%     18.6%      0.0%      0.0%  (n~12)
    María Fernanda Cabal             19.0%      0.0%     59.2%     21.8%      0.0%  (n~10)
    Roy Barreras                     68.4%      0.0%      0.0%     31.6%      0.0%  (n~9)
    Camilo Romero                    52.2%      7.6%     40.2%      0.0%      0.0%  (n~8)
    Enrique Peñalosa                 83.1%      0.0%     16.9%      0.0%      0.0%  (n~6)
    Claudia López                    34.0%      0.0%      0.0%     25.6%     40.4%  (n~5)
    Germán Vargas Lleras              7.7%      0.0%     92.3%      0.0%      0.0%  (n~4)
    Mauricio Cárdenas                26.3%     32.7%      0.0%      0.0%     41.0%  (n~3)
    Mauricio Lizcano                  0.0%      0.0%      0.0%      0.0%    100.0%  (n~0)

=================================================================
  TRASBASE  |  GAD3  |  2026-02-16  (n=2,473)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la EspVoto en blancoNo votaría     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.9%      0.8%      0.0%      0.0%      0.2%  (n~672)
    Abelardo de la Espriella          0.9%     97.7%      0.4%      0.0%      0.9%  (n~521)
    NS/NR                            22.3%     26.0%     25.7%      4.1%     22.0%  (n~258)
    Voto en blanco                   18.7%     15.4%     50.6%     14.3%      1.0%  (n~125)
    Paloma Valencia                   5.1%     72.9%     12.2%      7.7%      2.1%  (n~74)
    Claudia López                    49.2%     19.1%     22.6%      8.3%      0.8%  (n~59)
    Vicky Dávila                     25.8%     35.8%     20.0%     18.3%      0.0%  (n~45)
    Sergio Fajardo                   24.2%     48.8%     18.9%      8.1%      0.0%  (n~44)
    Santiago Botero                  25.7%     19.2%     23.0%     29.5%      2.4%  (n~41)
    Otro                             18.7%     16.7%     49.6%     13.0%      1.9%  (n~36)
    Juan Manuel Galán                31.8%     18.3%     29.7%     20.2%      0.0%  (n~18)
    Juan Carlos Pinzón               12.8%     44.3%     30.5%     12.4%      0.0%  (n~14)
    Enrique Peñalosa                 61.8%     29.7%      3.4%      5.0%      0.0%  (n~14)
    Roy Barreras                     35.7%     29.0%     27.7%      7.6%      0.0%  (n~13)
    Aníbal Gaviria                   65.1%      0.0%      7.4%     27.5%      0.0%  (n~7)
    Mauricio Cárdenas                44.7%     55.3%      0.0%      0.0%      0.0%  (n~5)
    Efraín Cepeda                   100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    David Luna                       13.2%     70.2%      0.0%      0.0%     16.6%  (n~4)
    Juan Daniel Oviedo               59.6%     12.9%     12.9%     14.7%      0.0%  (n~3)
    Germán Vargas Lleras              0.0%     74.6%      0.0%     25.4%      0.0%  (n~3)
    Carlos Caicedo                    0.0%     36.6%     63.4%      0.0%      0.0%  (n~2)
    Luis Carlos Reyes                 0.0%      0.0%    100.0%      0.0%      0.0%  (n~2)
    Mauricio Lizcano                  0.0%    100.0%      0.0%      0.0%      0.0%  (n~1)
    Felipe Córdoba                    0.0%    100.0%      0.0%      0.0%      0.0%  (n~1)
    Maurice Armitage                  0.0%     50.0%     50.0%      0.0%      0.0%  (n~0)
    Camilo Romero                     0.0%      0.0%    100.0%      0.0%      0.0%  (n~0)
    Paola Holguín                   100.0%      0.0%      0.0%      0.0%      0.0%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio FajardoVoto en blancoNo votaría     NS/NR
    ------------------------------------------------------------------------------
    Iván Cepeda                      94.9%      3.5%      0.2%      1.0%      0.4%  (n~672)
    Abelardo de la Espriella          3.7%     52.2%     19.2%     23.9%      1.1%  (n~521)
    NS/NR                            25.1%     24.1%     24.8%      6.4%     19.6%  (n~258)
    Voto en blanco                   17.2%     19.2%     51.6%     11.0%      1.0%  (n~125)
    Paloma Valencia                   7.1%     58.7%     17.4%     14.1%      2.7%  (n~74)
    Claudia López                    38.7%     27.4%     22.9%     10.9%      0.0%  (n~59)
    Vicky Dávila                     23.5%     42.2%     16.6%     17.7%      0.0%  (n~45)
    Sergio Fajardo                    8.6%     91.4%      0.0%      0.0%      0.0%  (n~44)
    Santiago Botero                  25.7%     18.4%     14.1%     39.4%      2.4%  (n~41)
    Otro                             19.8%     27.8%     41.8%     10.7%      0.0%  (n~36)
    Juan Manuel Galán                18.8%     62.8%      3.1%     11.7%      3.5%  (n~18)
    Juan Carlos Pinzón               12.8%     58.6%     12.9%     15.8%      0.0%  (n~14)
    Enrique Peñalosa                 31.0%     56.4%      7.6%      5.0%      0.0%  (n~14)
    Roy Barreras                     34.8%     25.6%     39.6%      0.0%      0.0%  (n~13)

In [16]:
trasbase('Invamer')

=================================================================
  TRASBASE  |  Invamer  |  2026-02-25  (n=3,801)
=================================================================

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la Esp   NingunoVoto en blanco      P233
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.1%      1.2%      0.6%      0.1%      0.0%  (n~1,266)
    Ninguno                           9.9%      6.9%     82.2%      1.0%      0.0%  (n~730)
    Abelardo de la Espriella          1.0%     98.2%      0.8%      0.0%      0.0%  (n~646)
    Claudia López                    43.3%     25.7%     27.2%      3.9%      0.0%  (n~429)
    Sergio Fajardo                   40.2%     27.5%     24.7%      7.6%      0.0%  (n~313)
    Paloma Valencia                  25.7%     55.4%     16.6%      2.3%      0.0%  (n~289)
    Voto en blanco                   12.2%      4.1%     20.2%     63.5%      0.0%  (n~66)
    Roy Barreras                     49.4%     29.9%     18.9%      1.8%      0.0%  (n~58)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio Fajardo   NingunoVoto en blanco      P232
    ------------------------------------------------------------------------------
    Iván Cepeda                      94.8%      4.2%      0.8%      0.2%      0.0%  (n~1,266)
    Ninguno                           6.2%      9.7%     82.8%      1.2%      0.0%  (n~730)
    Abelardo de la Espriella          6.9%     49.2%     39.9%      4.0%      0.0%  (n~646)
    Claudia López                    20.3%     58.1%     18.0%      3.5%      0.0%  (n~429)
    Sergio Fajardo                    2.9%     97.1%      0.0%      0.0%      0.0%  (n~313)
    Paloma Valencia                  16.0%     60.3%     21.1%      2.5%      0.0%  (n~289)
    Voto en blanco                    8.2%     22.5%     14.6%     54.7%      0.0%  (n~66)
    Roy Barreras                     31.0%     48.4%     18.5%      2.1%      0.0%  (n~58)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván Cepeda   NingunoPaloma ValenciaVoto en blanco      P256
    ------------------------------------------------------------------------------
    Iván Cepeda                      98.7%      0.3%      0.9%      0.1%      0.0%  (n~1,266)
    Ninguno                          10.8%     84.7%      3.5%      1.0%      0.0%  (n~730)
    Abelardo de la Espriella          8.4%     32.5%     54.5%      4.6%      0.0%  (n~646)
    Claudia López                    52.2%     22.7%     21.2%      3.9%      0.0%  (n~429)
    Sergio Fajardo                   42.4%     24.6%     26.6%      6.5%      0.0%  (n~313)
    Paloma Valencia                   8.9%      1.5%     89.6%      0.0%      0.0%  (n~289)
    Voto en blanco                   15.6%     22.4%      2.2%     59.8%      0.0%  (n~66)
    Roy Barreras                     55.4%     19.6%     21.0%      4.0%      0.0%  (n~58)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_espriella_vs_fajardo]
    Primera vuelta                 NingunoSergio FajardoAbelardo de la EspVoto en blanco      P231
    ------------------------------------------------------------------------------
    Iván Cepeda                      62.6%     23.8%      7.3%      6.3%      0.0%  (n~1,266)
    Ninguno                          84.3%      8.6%      6.3%      0.9%      0.0%  (n~730)
    Abelardo de la Espriella          0.1%      2.2%     97.7%      0.0%      0.0%  (n~646)
    Claudia López                    20.8%     59.4%     16.1%      3.6%      0.0%  (n~429)
    Sergio Fajardo                    0.0%     96.7%      3.3%      0.0%      0.0%  (n~313)
    Paloma Valencia                   9.4%     40.7%     47.7%      2.3%      0.0%  (n~289)
    Voto en blanco                   25.9%     22.3%      4.3%     47.6%      0.0%  (n~66)
    Roy Barreras                     20.9%     51.5%     25.4%      2.2%      0.0%  (n~58)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

=================================================================
  TRASBASE  |  Invamer  |  2026-04-25  (n=3,801)
=================================================================

  [sv_cepeda_vs_claudia]
    Primera vuelta              Iván Cepeda   NingunoClaudia LópezVoto en blanco      P258
    ------------------------------------------------------------------------------
    Iván Cepeda                      97.8%      0.0%      2.2%      0.0%      0.0%  (n~1,342)
    Abelardo de la Espriella          8.9%     42.5%     40.1%      8.5%      0.0%  (n~653)
    Paloma Valencia                  16.1%     28.2%     50.5%      5.1%      0.0%  (n~624)
    Ninguno                          25.5%     60.2%     11.8%      2.6%      0.0%  (n~573)
    Voto en blanco                   31.1%     28.4%     18.4%     22.2%      0.0%  (n~226)
    Claudia López                    13.2%      3.0%     83.7%      0.0%      0.0%  (n~146)
    Sergio Fajardo                   30.6%     15.9%     47.4%      6.0%      0.0%  (n~96)
    Santiago Botero                  32.5%     36.0%     27.9%      3.6%      0.0%  (n~52)
    Carlos Caicedo                   49.3%      7.0%     43.6%      0.0%      0.0%  (n~19)
    Sondra Macollins                 60.2%      0.0%     39.8%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 57.2%     15.4%     27.3%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            44.1%     16.3%     24.9%     14.7%      0.0%  (n~12)
    Miguel Uribe Londoño             58.5%     14.5%     26.9%      0.0%      0.0%  (n~11)
    Roy Barreras                     52.8%      0.0%     47.2%      0.0%      0.0%  (n~5)
    Gustavo Matamoros               100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la Esp   NingunoVoto en blanco      P233
    ------------------------------------------------------------------------------
    Iván Cepeda                      96.8%      2.4%      0.6%      0.1%      0.0%  (n~1,342)
    Abelardo de la Espriella          2.0%     97.5%      0.3%      0.2%      0.0%  (n~653)
    Paloma Valencia                  16.1%     67.1%     14.5%      2.3%      0.0%  (n~624)
    Ninguno                          23.1%     15.2%     59.5%      2.3%      0.0%  (n~573)
    Voto en blanco                   30.2%     20.8%     23.6%     25.3%      0.0%  (n~226)
    Claudia López                    48.1%     34.1%     13.6%      4.1%      0.0%  (n~146)
    Sergio Fajardo                   32.2%     44.9%     16.0%      6.9%      0.0%  (n~96)
    Santiago Botero                  34.5%     42.9%     22.6%      0.0%      0.0%  (n~52)
    Carlos Caicedo                   61.7%     25.4%     13.0%      0.0%      0.0%  (n~19)
    Sondra Macollins                 53.1%     46.9%      0.0%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 44.5%     47.1%      8.4%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            49.6%     15.9%     19.8%     14.7%      0.0%  (n~12)
    Miguel Uribe Londoño             60.6%     34.1%      5.3%      0.0%      0.0%  (n~11)
    Roy Barreras                     52.8%     21.3%      0.0%     26.0%      0.0%  (n~5)
    Gustavo Matamoros               100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio Fajardo   NingunoVoto en blanco      P232
    ------------------------------------------------------------------------------
    Iván Cepeda                      97.3%      2.3%      0.3%      0.0%      0.0%  (n~1,342)
    Abelardo de la Espriella          8.4%     58.6%     29.5%      3.6%      0.0%  (n~653)
    Paloma Valencia                  14.7%     61.6%     19.5%      4.2%      0.0%  (n~624)
    Ninguno                          26.7%     11.7%     59.4%      2.2%      0.0%  (n~573)
    Voto en blanco                   28.7%     22.8%     25.5%     23.0%      0.0%  (n~226)
    Claudia López                    50.2%     36.0%     13.8%      0.0%      0.0%  (n~146)
    Sergio Fajardo                   12.7%     85.0%      2.3%      0.0%      0.0%  (n~96)
    Santiago Botero                  41.0%     23.8%     31.6%      3.6%      0.0%  (n~52)
    Carlos Caicedo                   70.9%     16.1%     13.0%      0.0%      0.0%  (n~19)
    Sondra Macollins                 41.9%     58.1%      0.0%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 71.1%     13.5%     15.4%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            29.4%     67.1%      3.5%      0.0%      0.0%  (n~12)
    Miguel Uribe Londoño             70.7%     16.3%     13.0%      0.0%      0.0%  (n~11)
    Roy Barreras                     52.8%     26.7%      0.0%     20.6%      0.0%  (n~5)
    Gustavo Matamoros               100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván CepedaPaloma Valencia   NingunoVoto en blanco      P256
    ------------------------------------------------------------------------------
    Iván Cepeda                      96.3%      3.3%      0.4%      0.0%      0.0%  (n~1,342)
    Abelardo de la Espriella          6.3%     81.7%     11.1%      0.9%      0.0%  (n~653)
    Paloma Valencia                   3.0%     96.7%      0.3%      0.0%      0.0%  (n~624)
    Ninguno                          22.6%     23.2%     52.2%      2.0%      0.0%  (n~573)
    Voto en blanco                   27.7%     27.5%     20.9%     23.9%      0.0%  (n~226)
    Claudia López                    39.6%     49.5%      9.7%      1.3%      0.0%  (n~146)
    Sergio Fajardo                   29.5%     56.8%      9.4%      4.3%      0.0%  (n~96)
    Santiago Botero                  42.4%     32.4%     25.1%      0.0%      0.0%  (n~52)
    Carlos Caicedo                   63.6%     30.5%      5.9%      0.0%      0.0%  (n~19)
    Sondra Macollins                 40.1%     59.9%      0.0%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 53.0%     38.6%      8.4%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            50.5%     14.9%     19.8%     14.7%      0.0%  (n~12)
    Miguel Uribe Londoño             28.2%     66.5%      5.3%      0.0%      0.0%  (n~11)
    Roy Barreras                     52.8%     26.7%      0.0%     20.6%      0.0%  (n~5)
    Gustavo Matamoros               100.0%      0.0%      0.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_espriella_vs_fajardo]
    Primera vuelta              Abelardo de la Esp   NingunoSergio FajardoVoto en blanco      P267
    ------------------------------------------------------------------------------
    Iván Cepeda                      15.0%     46.3%     32.1%      6.7%      0.0%  (n~1,342)
    Abelardo de la Espriella         95.8%      1.1%      2.9%      0.2%      0.0%  (n~653)
    Paloma Valencia                  56.0%     14.3%     27.8%      1.8%      0.0%  (n~624)
    Ninguno                          15.4%     65.7%     15.9%      2.9%      0.0%  (n~573)
    Voto en blanco                   15.5%     29.1%     29.3%     26.0%      0.0%  (n~226)
    Claudia López                    20.2%     23.7%     52.0%      4.0%      0.0%  (n~146)
    Sergio Fajardo                   10.2%      2.3%     87.5%      0.0%      0.0%  (n~96)
    Santiago Botero                  46.5%     27.7%     22.3%      3.6%      0.0%  (n~52)
    Carlos Caicedo                   36.0%     42.0%     22.0%      0.0%      0.0%  (n~19)
    Sondra Macollins                 52.9%      8.8%     38.3%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 68.3%     19.9%     11.8%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            26.6%      3.5%     69.9%      0.0%      0.0%  (n~12)
    Miguel Uribe Londoño             42.8%     24.8%     32.5%      0.0%      0.0%  (n~11)
    Roy Barreras                     23.6%      0.0%     55.9%     20.6%      0.0%  (n~5)
    Gustavo Matamoros                 0.0%      0.0%    100.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

  [sv_fajardo_vs_valencia]
    Primera vuelta              Paloma Valencia   NingunoSergio FajardoVoto en blanco      P268
    ------------------------------------------------------------------------------
    Iván Cepeda                      12.5%     44.5%     36.0%      6.9%      0.0%  (n~1,342)
    Abelardo de la Espriella         75.6%     10.6%     12.5%      1.4%      0.0%  (n~653)
    Paloma Valencia                  94.6%      0.1%      4.9%      0.4%      0.0%  (n~624)
    Ninguno                          24.0%     58.9%     14.9%      2.1%      0.0%  (n~573)
    Voto en blanco                   27.6%     22.4%     22.5%     27.5%      0.0%  (n~226)
    Claudia López                    51.6%     18.7%     27.3%      2.4%      0.0%  (n~146)
    Sergio Fajardo                   13.4%      1.0%     85.6%      0.0%      0.0%  (n~96)
    Santiago Botero                  41.7%     29.5%     26.7%      2.1%      0.0%  (n~52)
    Carlos Caicedo                   44.3%     26.9%     28.8%      0.0%      0.0%  (n~19)
    Sondra Macollins                 55.4%      8.8%     35.7%      0.0%      0.0%  (n~15)
    Mauricio Lizcano                 53.9%     14.2%     31.9%      0.0%      0.0%  (n~14)
    Luis Gilberto Murillo            21.3%      9.2%     69.5%      0.0%      0.0%  (n~12)
    Miguel Uribe Londoño             68.4%      0.0%     31.6%      0.0%      0.0%  (n~11)
    Roy Barreras                     68.3%      0.0%     11.1%     20.6%      0.0%  (n~5)
    Gustavo Matamoros                 0.0%      0.0%    100.0%      0.0%      0.0%  (n~4)
    P245                              nan%      nan%      nan%      nan%      nan%  (n~0)

In [17]:
trasbase('CNC')

=================================================================
  TRASBASE  |  CNC  |  2026-02-20  (n=3,684)
=================================================================

  [sv_cardenas_vs_cepeda]
    Primera vuelta              Iván Cepeda   NingunoMauricio Cárdenas     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      99.0%      0.3%      0.5%      0.2%  (n~14,062,716)
    Abelardo de la Espriella          8.9%     49.6%     38.8%      2.6%  (n~6,641,961)
    NS/NR                            42.9%     15.8%      6.3%     34.9%  (n~3,489,434)
    Ninguno                          32.8%     56.2%      4.2%      6.8%  (n~2,486,649)
    Claudia López                    69.4%     14.3%     12.4%      3.9%  (n~2,055,982)
    Sergio Fajardo                   40.0%     35.6%     21.7%      2.7%  (n~1,914,474)
    Paloma Valencia                  21.2%     34.2%     42.4%      2.3%  (n~1,636,089)
    Juan Manuel Galán                46.1%     29.1%     20.4%      4.3%  (n~1,013,735)
    Vicky Dávila                     44.3%     21.7%     29.1%      4.9%  (n~784,469)
    Juan Daniel Oviedo               46.7%     22.8%     29.4%      1.2%  (n~734,723)
    Santiago Botero                  63.1%     23.9%     13.0%      0.0%  (n~688,898)
    Daniel Quintero                  72.4%      6.5%     13.9%      7.2%  (n~579,497)
    Enrique Peñalosa                 40.3%     17.4%     42.3%      0.0%  (n~492,483)
    Voto en blanco                   37.7%     43.5%      9.8%      9.0%  (n~477,134)
    Carlos Caicedo                   69.7%     13.3%     16.5%      0.5%  (n~472,041)
    Miguel Uribe Londoño             47.4%     12.6%     38.3%      1.7%  (n~402,390)
    Juan Carlos Pinzón               33.5%     17.5%     49.0%      0.0%  (n~382,118)
    Roy Barreras                     65.8%     18.3%     15.9%      0.0%  (n~359,473)
    Aníbal Gaviria                   51.1%     18.9%     22.6%      7.3%  (n~275,722)
    Sondra Macollins                 21.9%     32.8%     45.4%      0.0%  (n~261,854)
    David Luna                       39.6%     36.9%     23.5%      0.0%  (n~206,469)
    Mauricio Cárdenas                27.5%      0.0%     72.5%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     29.2%      3.0%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      0.0%      6.4%      0.0%  (n~36,909)
    Mauricio Lizcano                 84.8%      0.0%     15.2%      0.0%  (n~27,679)
    Juan Fernando Cristo             15.3%     84.7%      0.0%      0.0%  (n~12,148)

  [sv_cepeda_vs_claudia]
    Primera vuelta              Iván CepedaClaudia López   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      97.4%      1.8%      0.4%      0.3%  (n~14,062,716)
    Abelardo de la Espriella          6.9%     33.4%     57.0%      2.7%  (n~6,641,961)
    NS/NR                            31.4%     23.3%     16.6%     28.7%  (n~3,489,434)
    Ninguno                          27.0%     19.3%     48.5%      5.2%  (n~2,486,649)
    Claudia López                    11.5%     88.5%      0.0%      0.0%  (n~2,055,982)
    Sergio Fajardo                   31.3%     44.3%     21.9%      2.4%  (n~1,914,474)
    Paloma Valencia                  21.0%     36.3%     42.4%      0.3%  (n~1,636,089)
    Juan Manuel Galán                40.9%     40.9%     13.8%      4.3%  (n~1,013,735)
    Vicky Dávila                     43.7%     40.1%     12.7%      3.6%  (n~784,469)
    Juan Daniel Oviedo               40.3%     45.4%     14.4%      0.0%  (n~734,723)
    Santiago Botero                  59.1%     25.7%     15.2%      0.0%  (n~688,898)
    Daniel Quintero                  61.6%     28.1%      8.8%      1.5%  (n~579,497)
    Enrique Peñalosa                 31.4%     55.4%     11.1%      2.0%  (n~492,483)
    Voto en blanco                   22.2%     31.7%     33.2%     12.8%  (n~477,134)
    Carlos Caicedo                   72.2%     23.1%      4.2%      0.5%  (n~472,041)
    Miguel Uribe Londoño             41.6%     31.0%     19.3%      8.2%  (n~402,390)
    Juan Carlos Pinzón               31.4%     47.4%     18.1%      3.2%  (n~382,118)
    Roy Barreras                     58.9%     22.8%     18.3%      0.0%  (n~359,473)
    Aníbal Gaviria                   34.2%     47.6%     15.2%      3.0%  (n~275,722)
    Sondra Macollins                 23.8%     76.2%      0.0%      0.0%  (n~261,854)
    David Luna                       20.1%     51.8%     28.1%      0.0%  (n~206,469)
    Mauricio Cárdenas                25.6%     68.8%      5.7%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     21.4%     10.7%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      0.0%      6.4%      0.0%  (n~36,909)
    Mauricio Lizcano                 84.8%     15.2%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     33.1%     66.9%      0.0%  (n~12,148)

  [sv_cepeda_vs_davila]
    Primera vuelta              Iván CepedaVicky Dávila   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      98.8%      0.5%      0.5%      0.2%  (n~14,062,716)
    Abelardo de la Espriella          9.0%     57.4%     32.2%      1.4%  (n~6,641,961)
    NS/NR                            37.1%     18.5%     15.3%     29.1%  (n~3,489,434)
    Ninguno                          32.9%      9.1%     52.8%      5.2%  (n~2,486,649)
    Claudia López                    57.4%     29.0%     11.7%      1.9%  (n~2,055,982)
    Sergio Fajardo                   37.2%     29.6%     32.2%      0.9%  (n~1,914,474)
    Paloma Valencia                  27.1%     50.7%     20.5%      1.7%  (n~1,636,089)
    Juan Manuel Galán                48.0%     34.4%     12.3%      5.3%  (n~1,013,735)
    Vicky Dávila                     15.4%     82.1%      2.5%      0.0%  (n~784,469)
    Juan Daniel Oviedo               49.0%     25.3%     25.7%      0.0%  (n~734,723)
    Santiago Botero                  65.4%     16.1%     18.5%      0.0%  (n~688,898)
    Daniel Quintero                  71.6%     18.4%     10.0%      0.0%  (n~579,497)
    Enrique Peñalosa                 37.1%     46.4%     15.9%      0.5%  (n~492,483)
    Voto en blanco                   28.7%     21.6%     47.1%      2.6%  (n~477,134)
    Carlos Caicedo                   73.1%     23.1%      1.1%      2.8%  (n~472,041)
    Miguel Uribe Londoño             39.2%     30.9%     22.1%      7.8%  (n~402,390)
    Juan Carlos Pinzón               32.3%     51.0%     16.7%      0.0%  (n~382,118)
    Roy Barreras                     69.8%     11.9%     18.3%      0.0%  (n~359,473)
    Aníbal Gaviria                   47.1%     31.9%     14.6%      6.4%  (n~275,722)
    Sondra Macollins                 23.4%     43.8%     32.8%      0.0%  (n~261,854)
    David Luna                       48.9%     24.1%     27.0%      0.0%  (n~206,469)
    Mauricio Cárdenas                61.7%     31.2%      7.1%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%      3.0%     29.2%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      0.0%      6.4%      0.0%  (n~36,909)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo             15.3%      0.0%     84.7%      0.0%  (n~12,148)

  [sv_cepeda_vs_espriella]
    Primera vuelta              Iván CepedaAbelardo de la Esp   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      97.9%      1.4%      0.3%      0.3%  (n~14,062,716)
    Abelardo de la Espriella          1.2%     98.5%      0.1%      0.2%  (n~6,641,961)
    NS/NR                            35.5%     16.7%     13.0%     34.7%  (n~3,489,434)
    Ninguno                          30.1%     10.5%     52.7%      6.7%  (n~2,486,649)
    Claudia López                    64.1%     20.4%     11.8%      3.8%  (n~2,055,982)
    Sergio Fajardo                   40.5%     25.9%     31.2%      2.4%  (n~1,914,474)
    Paloma Valencia                  19.0%     69.4%      9.8%      1.8%  (n~1,636,089)
    Juan Manuel Galán                46.0%     24.7%     24.7%      4.6%  (n~1,013,735)
    Vicky Dávila                     40.9%     37.4%     12.7%      9.0%  (n~784,469)
    Juan Daniel Oviedo               46.6%     27.2%     25.1%      1.1%  (n~734,723)
    Santiago Botero                  56.0%     29.6%     14.3%      0.0%  (n~688,898)
    Daniel Quintero                  70.9%     12.7%     10.7%      5.8%  (n~579,497)
    Enrique Peñalosa                 42.6%     47.3%      9.6%      0.5%  (n~492,483)
    Voto en blanco                   33.6%      8.6%     41.1%     16.7%  (n~477,134)
    Carlos Caicedo                   75.1%     14.4%      1.6%      8.8%  (n~472,041)
    Miguel Uribe Londoño             46.2%     37.5%      7.8%      8.5%  (n~402,390)
    Juan Carlos Pinzón               27.5%     68.5%      4.0%      0.0%  (n~382,118)
    Roy Barreras                     53.4%     18.2%     28.4%      0.0%  (n~359,473)
    Aníbal Gaviria                   17.7%     44.2%     29.4%      8.6%  (n~275,722)
    Sondra Macollins                 65.7%      0.0%     34.3%      0.0%  (n~261,854)
    David Luna                       35.9%     50.8%      4.8%      8.4%  (n~206,469)
    Mauricio Cárdenas                48.9%     41.0%     10.1%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     21.4%     10.7%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      6.4%      0.0%      0.0%  (n~36,909)
    Mauricio Lizcano                 84.8%     15.2%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     15.3%     84.7%      0.0%  (n~12,148)

  [sv_cepeda_vs_fajardo]
    Primera vuelta              Iván CepedaSergio Fajardo   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      97.7%      1.9%      0.1%      0.4%  (n~14,062,716)
    Abelardo de la Espriella          7.3%     59.2%     31.2%      2.3%  (n~6,641,961)
    NS/NR                            33.3%     19.9%      9.6%     37.3%  (n~3,489,434)
    Ninguno                          32.7%     11.3%     49.1%      6.9%  (n~2,486,649)
    Claudia López                    52.9%     32.5%     11.2%      3.4%  (n~2,055,982)
    Sergio Fajardo                   11.6%     84.8%      3.4%      0.2%  (n~1,914,474)
    Paloma Valencia                  19.6%     63.0%     16.8%      0.6%  (n~1,636,089)
    Juan Manuel Galán                36.3%     44.3%     12.6%      6.8%  (n~1,013,735)
    Vicky Dávila                     31.6%     47.5%     13.7%      7.3%  (n~784,469)
    Juan Daniel Oviedo               33.9%     52.1%     14.0%      0.0%  (n~734,723)
    Santiago Botero                  55.3%     34.5%      9.0%      1.2%  (n~688,898)
    Daniel Quintero                  42.8%     46.9%     10.3%      0.0%  (n~579,497)
    Enrique Peñalosa                 25.2%     71.6%      3.1%      0.0%  (n~492,483)
    Voto en blanco                   34.4%     16.9%     36.1%     12.5%  (n~477,134)
    Carlos Caicedo                   74.7%     15.4%      1.1%      8.8%  (n~472,041)
    Miguel Uribe Londoño             38.4%     51.0%      9.8%      0.7%  (n~402,390)
    Juan Carlos Pinzón               15.3%     72.6%      9.6%      2.5%  (n~382,118)
    Roy Barreras                     36.5%     42.7%     20.8%      0.0%  (n~359,473)
    Aníbal Gaviria                   39.7%     57.3%      3.0%      0.0%  (n~275,722)
    Sondra Macollins                 21.9%     45.4%     32.8%      0.0%  (n~261,854)
    David Luna                       37.3%     53.6%      9.2%      0.0%  (n~206,469)
    Mauricio Cárdenas                51.9%     44.1%      4.0%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     32.2%      0.0%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      6.4%      0.0%      0.0%  (n~36,909)
    Mauricio Lizcano                 14.0%     86.0%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     33.1%     66.9%      0.0%  (n~12,148)

  [sv_cepeda_vs_galan]
    Primera vuelta              Iván CepedaJuan Manuel Galán   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      97.9%      1.7%      0.1%      0.3%  (n~14,062,716)
    Abelardo de la Espriella          6.7%     60.5%     29.8%      3.0%  (n~6,641,961)
    NS/NR                            38.6%     16.1%     12.3%     33.0%  (n~3,489,434)
    Ninguno                          31.0%     11.6%     51.2%      6.2%  (n~2,486,649)
    Claudia López                    58.4%     27.9%     11.7%      2.0%  (n~2,055,982)
    Sergio Fajardo                   35.6%     41.8%     17.9%      4.7%  (n~1,914,474)
    Paloma Valencia                  16.6%     63.4%     19.8%      0.2%  (n~1,636,089)
    Juan Manuel Galán                21.0%     76.7%      2.2%      0.0%  (n~1,013,735)
    Vicky Dávila                     44.1%     37.5%     15.0%      3.4%  (n~784,469)
    Juan Daniel Oviedo               38.5%     49.6%     11.9%      0.0%  (n~734,723)
    Santiago Botero                  54.0%     30.0%     16.0%      0.0%  (n~688,898)
    Daniel Quintero                  66.0%     20.8%      6.0%      7.2%  (n~579,497)
    Enrique Peñalosa                 34.3%     63.9%      1.5%      0.3%  (n~492,483)
    Voto en blanco                   32.0%     19.1%     46.0%      2.9%  (n~477,134)
    Carlos Caicedo                   66.7%     13.4%     13.3%      6.6%  (n~472,041)
    Miguel Uribe Londoño             38.4%     36.1%     23.8%      1.7%  (n~402,390)
    Juan Carlos Pinzón               29.7%     68.3%      2.0%      0.0%  (n~382,118)
    Roy Barreras                     60.3%     25.3%     14.4%      0.0%  (n~359,473)
    Aníbal Gaviria                   51.1%     31.6%     10.0%      7.3%  (n~275,722)
    Sondra Macollins                 20.4%     46.8%     32.8%      0.0%  (n~261,854)
    David Luna                       46.6%     39.2%     14.2%      0.0%  (n~206,469)
    Mauricio Cárdenas                47.4%     48.7%      4.0%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     21.4%     10.7%      0.0%  (n~61,932)
    Maurice Armitage                 79.5%     20.5%      0.0%      0.0%  (n~36,909)
    Mauricio Lizcano                100.0%      0.0%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     15.3%     84.7%      0.0%  (n~12,148)

  [sv_cepeda_vs_gaviria]
    Primera vuelta              Iván CepedaAníbal Gaviria   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      98.8%      0.8%      0.1%      0.2%  (n~14,062,716)
    Abelardo de la Espriella          8.1%     45.2%     43.6%      3.1%  (n~6,641,961)
    NS/NR                            38.9%     11.1%     14.4%     35.6%  (n~3,489,434)
    Ninguno                          32.2%      7.1%     55.3%      5.4%  (n~2,486,649)
    Claudia López                    62.9%     19.9%     11.4%      5.8%  (n~2,055,982)
    Sergio Fajardo                   38.7%     38.7%     18.6%      4.0%  (n~1,914,474)
    Paloma Valencia                  21.5%     46.3%     28.6%      3.6%  (n~1,636,089)
    Juan Manuel Galán                42.8%     31.2%     22.2%      3.8%  (n~1,013,735)
    Vicky Dávila                     43.8%     36.6%     16.5%      3.0%  (n~784,469)
    Juan Daniel Oviedo               40.5%     42.2%     17.3%      0.0%  (n~734,723)
    Santiago Botero                  71.1%     13.9%     15.0%      0.0%  (n~688,898)
    Daniel Quintero                  69.8%     23.9%      4.9%      1.5%  (n~579,497)
    Enrique Peñalosa                 35.9%     48.9%     13.2%      2.0%  (n~492,483)
    Voto en blanco                   35.6%     12.4%     49.1%      2.9%  (n~477,134)
    Carlos Caicedo                   77.4%      2.1%     13.3%      7.1%  (n~472,041)
    Miguel Uribe Londoño             40.5%     31.7%     19.3%      8.5%  (n~402,390)
    Juan Carlos Pinzón               36.0%     52.0%     12.1%      0.0%  (n~382,118)
    Roy Barreras                     65.0%     17.3%     17.7%      0.0%  (n~359,473)
    Aníbal Gaviria                   20.4%     79.6%      0.0%      0.0%  (n~275,722)
    Sondra Macollins                 65.7%      1.6%     32.8%      0.0%  (n~261,854)
    David Luna                       39.6%     23.5%     36.9%      0.0%  (n~206,469)
    Mauricio Cárdenas                55.2%     39.4%      5.4%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     32.2%      0.0%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      6.4%      0.0%      0.0%  (n~36,909)
    Mauricio Lizcano                 84.8%     15.2%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     15.3%     84.7%      0.0%  (n~12,148)

  [sv_cepeda_vs_valencia]
    Primera vuelta              Iván CepedaPaloma Valencia   Ninguno     NS/NR
    --------------------------------------------------------------------
    Iván Cepeda                      99.3%      0.4%      0.1%      0.2%  (n~14,062,716)
    Abelardo de la Espriella          7.6%     68.5%     21.7%      2.1%  (n~6,641,961)
    NS/NR                            38.8%     17.0%     11.0%     33.1%  (n~3,489,434)
    Ninguno                          29.3%     12.3%     53.2%      5.2%  (n~2,486,649)
    Claudia López                    64.4%     16.9%     15.9%      2.9%  (n~2,055,982)
    Sergio Fajardo                   40.5%     35.3%     21.4%      2.8%  (n~1,914,474)
    Paloma Valencia                   8.3%     90.3%      1.4%      0.0%  (n~1,636,089)
    Juan Manuel Galán                45.5%     28.4%     19.5%      6.5%  (n~1,013,735)
    Vicky Dávila                     40.0%     41.4%     17.1%      1.4%  (n~784,469)
    Juan Daniel Oviedo               46.0%     36.1%     17.9%      0.0%  (n~734,723)
    Santiago Botero                  56.5%     26.9%     16.6%      0.0%  (n~688,898)
    Daniel Quintero                  74.7%      9.9%      9.8%      5.6%  (n~579,497)
    Enrique Peñalosa                 36.4%     54.8%      6.4%      2.3%  (n~492,483)
    Voto en blanco                   35.1%     16.1%     38.3%     10.5%  (n~477,134)
    Carlos Caicedo                   84.8%      1.4%     13.3%      0.5%  (n~472,041)
    Miguel Uribe Londoño             49.0%     27.2%     21.0%      2.8%  (n~402,390)
    Juan Carlos Pinzón               41.4%     48.2%     10.4%      0.0%  (n~382,118)
    Roy Barreras                     60.4%     22.0%     17.7%      0.0%  (n~359,473)
    Aníbal Gaviria                   49.8%     34.4%     12.7%      3.0%  (n~275,722)
    Sondra Macollins                 65.7%      1.6%     32.8%      0.0%  (n~261,854)
    David Luna                       48.9%     19.1%     31.9%      0.0%  (n~206,469)
    Mauricio Cárdenas                59.7%     37.1%      3.2%      0.0%  (n~170,907)
    Luis Gilberto Murillo            67.8%     21.4%     10.7%      0.0%  (n~61,932)
    Maurice Armitage                 93.6%      6.4%      0.0%      0.0%  (n~36,909)
    Mauricio Lizcano                 84.8%     15.2%      0.0%      0.0%  (n~27,679)
    Juan Fernando Cristo              0.0%     15.3%     84.7%      0.0%  (n~12,148)

=================================================================
  TRASBASE  |  CNC  |  2026-03-16  (n=2,157)
=================================================================

  [sv_barreras_vs_cepeda]
    Primera vuelta              Iván Cepeda   NingunoRoy Barreras     NS/NR
    --------------------------------------------------------------------

## ID resultado por encuesta

In [18]:

# Tabla de IDs: (encuestadora normalizada, fecha YYYY-MM-DD) → id_resultado
ID_MAP = {
    ("Atlas Intel",  "2026-01-09"): "574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5",
    ("Atlas Intel",  "2026-02-05"): "dd8c6d8f-8414-46cc-a4a3-0d4c0cb5d727",
    ("Atlas Intel",  "2026-02-28"): "8f1dc697-304b-41ca-a83c-bfa5e8df23c9",
    ("Atlas Intel",  "2026-03-12"): "8e690c54-bb74-4905-8432-c1b5d5ba995a",
    ("Atlas Intel",  "2026-04-10"): "ab056bb2-8345-49d7-a4bf-6428896acdf8",
    ("CNC",          "2026-02-20"): "f8780e6c-447a-4345-9934-9b711f849120",
    ("CNC",          "2026-03-16"): "4d6479aa-58b2-4399-924c-03ffb307054d",
    ("GAD3",         "2026-01-13"): "ccd56d3f-a8e8-4de4-a451-134c43038029",
    ("GAD3",         "2026-02-16"): "1197a175-79ed-48e8-9822-ced8ec0998bb",
    ("GAD3",         "2026-03-16"): "762692c5-2f67-4b91-8fdf-93b662e7f7e7",
    ("Invamer",      "2026-02-25"): "1fb623ba-a1f0-42b3-8c08-9580d41eca23",
    ("Invamer",      "2026-04-25"): "a0c3e256-a5b3-4157-bae4-eb5ff479fb7f",
}

def _enc_key(enc):
    """Normaliza el nombre de la encuestadora al prefijo usado en ID_MAP."""
    if enc.startswith("Invamer"):
        return "Invamer"
    return enc

def get_id(encuestadora, fecha):
    """Devuelve el id_resultado dado encuestadora y fecha (str o Timestamp)."""
    key = (_enc_key(encuestadora), str(fecha)[:10])
    return ID_MAP.get(key)

# Agregar columna id_resultado al df
df["id_resultado"] = df.apply(lambda row: get_id(row["encuestadora"], row["fecha"]), axis=1)

# Verificar cobertura
print("Cobertura de id_resultado:")
print(df.groupby(["encuestadora", "fecha"])["id_resultado"].first().to_string())
print(f"\nFilas sin ID: {df['id_resultado'].isna().sum()}")

Cobertura de id_resultado:
encuestadora  fecha
Atlas Intel   2026-01-09    574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
              2026-02-05    dd8c6d8f-8414-46cc-a4a3-0d4c0cb5d727
              2026-02-28    8f1dc697-304b-41ca-a83c-bfa5e8df23c9
              2026-03-12    8e690c54-bb74-4905-8432-c1b5d5ba995a
              2026-04-10    ab056bb2-8345-49d7-a4bf-6428896acdf8
CNC           2026-02-20    f8780e6c-447a-4345-9934-9b711f849120
              2026-03-16    4d6479aa-58b2-4399-924c-03ffb307054d
GAD3          2026-01-13    ccd56d3f-a8e8-4de4-a451-134c43038029
              2026-02-16    1197a175-79ed-48e8-9822-ced8ec0998bb
              2026-03-16    762692c5-2f67-4b91-8fdf-93b662e7f7e7
Invamer       2026-02-25    1fb623ba-a1f0-42b3-8c08-9580d41eca23
              2026-04-25    a0c3e256-a5b3-4157-bae4-eb5ff479fb7f

Filas sin ID: 0

In [19]:
df.columns

Index(['encuestadora', 'fecha', 'factor', 'departamento', 'municipio',
       'region', 'zona', 'genero', 'edad_grupo', 'estrato', 'educacion',
       'primera_vuelta', 'primera_vuelta_espontanea', 'sv_barreras_vs_cepeda',
       'sv_cardenas_vs_cepeda', 'sv_cepeda_vs_claudia', 'sv_cepeda_vs_davila',
       'sv_cepeda_vs_espriella', 'sv_cepeda_vs_fajardo', 'sv_cepeda_vs_galan',
       'sv_cepeda_vs_gaviria', 'sv_cepeda_vs_lizcano', 'sv_cepeda_vs_murillo',
       'sv_cepeda_vs_pinzon', 'sv_cepeda_vs_uribe_londono',
       'sv_cepeda_vs_valencia', 'sv_espriella_vs_fajardo',
       'sv_espriella_vs_valencia', 'sv_fajardo_vs_pinzon',
       'sv_fajardo_vs_valencia', 'aprobacion_petro', 'id_resultado'],
      dtype='str')

In [20]:
df[df["encuestadora"]=="CNC"]["fecha"].value_counts()

fecha
2026-02-20    3684
2026-03-16    2157
Name: count, dtype: int64

In [21]:
res = (
    df[(df["encuestadora"] == "CNC") & (df["fecha"] == "2026-03-16")]
    .groupby("primera_vuelta")["factor"]
    .sum()
)

res_norm = res / res.sum()

In [22]:
res_norm

primera_vuelta
Abelardo de la Espriella    0.154573
Carlos Caicedo              0.001248
Clara López                 0.003005
Claudia López               0.036998
Gustavo Matamoros           0.002397
Iván Cepeda                 0.344733
Luis Gilberto Murillo       0.002191
Mauricio Lizcano            0.001859
Miguel Uribe Londoño        0.010283
NS/NR                       0.079652
Ninguno                     0.018580
Paloma Valencia             0.221839
Roy Barreras                0.004786
Santiago Botero             0.012690
Sergio Fajardo              0.035929
Sondra Macollins            0.003876
Voto en blanco              0.065361
Name: factor, dtype: float64

In [23]:

# ── Versión generalizada: cruza cualquier par de columnas ──────────────────

def build_crosstab_long(df, col_fila, col_columna, escenarios=None):
    """
    Cruza col_fila × col_columna con % ponderados, en formato long.

    Sin escenarios: cruza las dos columnas directamente.
    Con escenarios (dict {nombre: col_real_en_df}): itera sobre cada
      escenario y añade columna 'escenario'; col_columna es el nombre de salida.

    Columnas resultado:
        encuestadora, fecha, [escenario,] <col_fila>, <col_columna>, pct
    """
    def _pair(sub, fila, col):
        partes = []
        for (enc, fecha), grupo in sub.groupby(['encuestadora', 'fecha']):
            ct = grupo.groupby([fila, col])['factor'].sum().reset_index()
            tots = ct.groupby(fila)['factor'].sum()
            ct['_total_fila'] = ct[fila].map(tots)
            ct = ct[ct['_total_fila'] > 0]
            if ct.empty:
                continue
            ct['pct'] = (ct['factor'] / ct['_total_fila'] * 100).round(1)
            ct = ct.drop(columns=['_total_fila'])
            ct['encuestadora'] = enc
            ct['fecha'] = fecha
            partes.append(ct[['encuestadora', 'fecha', fila, col, 'pct']])
        return pd.concat(partes, ignore_index=True) if partes else pd.DataFrame()

    if escenarios:
        bloques = []
        for nombre, col_real in escenarios.items():
            if col_real not in df.columns:
                continue
            sub = df[df[col_fila].notna() & df[col_real].notna()]
            bloque = _pair(sub, col_fila, col_real)
            if bloque.empty:
                continue
            bloque = bloque.rename(columns={col_real: col_columna})
            bloque.insert(2, 'escenario', nombre)
            bloques.append(bloque)
        return pd.concat(bloques, ignore_index=True) if bloques else pd.DataFrame()

    sub = df[df[col_fila].notna() & df[col_columna].notna()]
    return _pair(sub, col_fila, col_columna)


# Los 6 escenarios clave (reemplaza el ESCENARIOS anterior con los 6 completos)
ESCENARIOS_6 = {
    'cepeda_vs_paloma':    'sv_cepeda_vs_valencia',
    'cepeda_vs_abelardo':  'sv_cepeda_vs_espriella',
    'cepeda_vs_fajardo':   'sv_cepeda_vs_fajardo',
    'paloma_vs_fajardo':   'sv_fajardo_vs_valencia',
    'abelardo_vs_fajardo': 'sv_espriella_vs_fajardo',
    'paloma_vs_abelardo':  'sv_espriella_vs_valencia',
}

# Uso: replicar trasbase de los 6 escenarios
df_long6 = build_crosstab_long(df, 'primera_vuelta', 'voto_sv', escenarios=ESCENARIOS_6)
print(f"Filas: {len(df_long6):,}  |  Escenarios: {df_long6['escenario'].unique().tolist()}")
df_long6.head(10)

Filas: 3,282  |  Escenarios: ['cepeda_vs_paloma', 'cepeda_vs_abelardo', 'cepeda_vs_fajardo', 'paloma_vs_fajardo', 'abelardo_vs_fajardo', 'paloma_vs_abelardo']

,encuestadora,fecha,escenario,primera_vuelta,voto_sv,pct
0,Atlas Intel,2026-01-09,cepeda_vs_paloma,Abelardo de la Espriella,Iván Cepeda,5.5
1,Atlas Intel,2026-01-09,cepeda_vs_paloma,Abelardo de la Espriella,No sé,4.3
2,Atlas Intel,2026-01-09,cepeda_vs_paloma,Abelardo de la Espriella,Paloma Valencia,71.7
3,Atlas Intel,2026-01-09,cepeda_vs_paloma,Abelardo de la Espriella,Voto en blanco,18.5
4,Atlas Intel,2026-01-09,cepeda_vs_paloma,Aníbal Gaviria,Iván Cepeda,31.6
5,Atlas Intel,2026-01-09,cepeda_vs_paloma,Aníbal Gaviria,No sé,36.2
6,Atlas Intel,2026-01-09,cepeda_vs_paloma,Aníbal Gaviria,Paloma Valencia,27.9
7,Atlas Intel,2026-01-09,cepeda_vs_paloma,Aníbal Gaviria,Voto en blanco,4.3
8,Atlas Intel,2026-01-09,cepeda_vs_paloma,Claudia López,Iván Cepeda,23.5
9,Atlas Intel,2026-01-09,cepeda_vs_paloma,Claudia López,No sé,5.5

In [24]:

# ── Ponderación entre encuestas ────────────────────────────────────────────

# w_total por (encuestadora, fecha_pub) — tabla de pesos suministrada
PESOS = {
    ('Invamer',     '2026-04-25'): 1766,
    ('Atlas Intel', '2026-04-10'):  707,
    ('GAD3',        '2026-03-16'):   89,
    ('CNC',         '2026-03-16'):  220,
    ('Atlas Intel', '2026-03-12'):  175,
    ('Atlas Intel', '2026-02-28'):   29,
    ('Invamer',     '2026-02-25'):   22,
    ('CNC',         '2026-02-20'):   26,
    ('GAD3',        '2026-02-16'):   15,
    ('Atlas Intel', '2026-02-05'):   29,
    ('GAD3',        '2026-01-13'):    1,
    ('Atlas Intel', '2026-01-09'):  175,
}


def ponderar(df_vals, col_valor='pct', groupby=None,
             col_enc='encuestadora', col_fecha='fecha'):
    """
    Promedio ponderado de col_valor usando PESOS.

    Sin groupby  → escalar (promedio global).
    Con groupby  → DataFrame con una fila por grupo y columna '<col_valor>_pond'.

    Solo se usan filas cuyo (encuestadora, fecha) tenga peso en PESOS.
    El promedio es:  sum(valor * w) / sum(w)
    """
    d = df_vals.copy()
    d['_w'] = d.apply(
        lambda r: PESOS.get((r[col_enc], str(r[col_fecha])[:10]), 0), axis=1
    )
    d = d[d['_w'] > 0]
    if d.empty:
        return None

    if groupby:
        def _wavg(g):
            tw = g['_w'].sum()
            return round((g[col_valor] * g['_w']).sum() / tw, 2) if tw else None
        return (
            d.groupby(groupby)
             .apply(_wavg, include_groups=False)
             .reset_index(name=f'{col_valor}_pond')
        )

    tw = d['_w'].sum()
    return round((d[col_valor] * d['_w']).sum() / tw, 2)

def aplicar_peso_encuesta(df_vals, col_enc='encuestadora', col_fecha='fecha'):
    d = df_vals.copy()
    d['_w_enc'] = d.apply(lambda r: PESOS.get((r[col_enc], str(r[col_fecha])[:10]), 0), axis=1)
    return d[d['_w_enc'] > 0].copy()

def crosstab_ponderado(df_vals, fila, columna, usar_pesos_encuesta=False, col_enc='encuestadora', col_fecha='fecha'):
    sub = df_vals[df_vals[fila].notna() & df_vals[columna].notna()].copy()
    if sub.empty:
        return pd.DataFrame()
    if usar_pesos_encuesta:
        sub = aplicar_peso_encuesta(sub, col_enc=col_enc, col_fecha=col_fecha)
        if sub.empty:
            return pd.DataFrame()
        peso_col = '_w_enc'
        sub['_peso_total'] = sub['factor'] * sub[peso_col]
        peso_col = '_peso_total'
    else:
        peso_col = 'factor'
    ct = sub.groupby([fila, columna])[peso_col].sum().unstack(fill_value=0)
    total_fila = ct.sum(axis=1).replace(0, pd.NA)
    return (ct.div(total_fila, axis=0) * 100).round(1).fillna(0)

def sesgo_por_candidato_df(subdf, col_candidato='primera_vuelta', col_demo='edad_grupo'):
    validos = subdf[subdf[col_candidato].notna() & subdf[col_demo].notna()].copy()
    if validos.empty:
        return pd.DataFrame()
    ct_pond = validos.pivot_table(index=col_candidato, columns=col_demo, values='factor', aggfunc='sum', fill_value=0)
    ct_raw = validos.pivot_table(index=col_candidato, columns=col_demo, values='factor', aggfunc='size', fill_value=0)
    pond_total = ct_pond.sum(axis=1).replace(0, pd.NA)
    raw_total = ct_raw.sum(axis=1).replace(0, pd.NA)
    ct_pond = (ct_pond.div(pond_total, axis=0) * 100).round(1).fillna(0)
    ct_raw = (ct_raw.div(raw_total, axis=0) * 100).round(1).fillna(0)
    pond = ct_pond.reset_index().melt(id_vars=col_candidato, var_name=col_demo, value_name='ponderado_pct')
    raw = ct_raw.reset_index().melt(id_vars=col_candidato, var_name=col_demo, value_name='sin_peso_pct')
    tabla = pond.merge(raw, on=[col_candidato, col_demo], how='outer').fillna(0)
    tabla['sesgo_pp'] = (tabla['ponderado_pct'] - tabla['sin_peso_pct']).round(1)
    return tabla.sort_values([col_candidato, 'sesgo_pp'], ascending=[True, False])


# Ejemplo de uso: ponderar(df_long6, groupby=['escenario', 'primera_vuelta', 'voto_sv'])

In [25]:
df[["edad_grupo","encuestadora"]].value_counts()

edad_grupo  encuestadora
45-59       Atlas Intel     7459
35-44       Atlas Intel     5904
25-34       Atlas Intel     5224
60+         Atlas Intel     5202
55+         Invamer         2547
18-24       Atlas Intel     2405
55+         CNC             1753
            GAD3            1670
25-34       Invamer         1474
35-44       Invamer         1358
45-54       Invamer         1239
25-34       CNC             1188
35-44       CNC             1084
45-54       CNC             1073
18-24       Invamer          982
35-44       GAD3             801
45-54       GAD3             793
18-24       CNC              743
25-34       GAD3             628
35-54       GAD3             485
18-34       GAD3             295
18-24       GAD3             208
Name: count, dtype: int64

In [26]:
df

,encuestadora,fecha,factor,departamento,municipio,region,zona,genero,edad_grupo,estrato,...,sv_cepeda_vs_murillo,sv_cepeda_vs_pinzon,sv_cepeda_vs_uribe_londono,sv_cepeda_vs_valencia,sv_espriella_vs_fajardo,sv_espriella_vs_valencia,sv_fajardo_vs_pinzon,sv_fajardo_vs_valencia,aprobacion_petro,id_resultado
0,Atlas Intel,2026-01-09,2.650916e-06,Santander,Barichara,Central,NaN,Hombre,45-59,NaN,...,NaN,Voto en blanco,NaN,Iván Cepeda,Sergio Fajardo,NaN,NaN,NaN,Regular,574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
1,Atlas Intel,2026-01-09,6.110878e-07,Antioquia,Medellín,Central,NaN,Hombre,60+,NaN,...,NaN,Voto en blanco,NaN,Voto en blanco,Voto en blanco,NaN,NaN,NaN,Malo / muy malo,574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
2,Atlas Intel,2026-01-09,7.076182e-07,Antioquia,Medellín,Central,NaN,Hombre,35-44,NaN,...,NaN,Juan Carlos Pinzón,NaN,Paloma Valencia,Sergio Fajardo,NaN,NaN,NaN,Malo / muy malo,574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
3,Atlas Intel,2026-01-09,7.413255e-07,Antioquia,Medellín,Central,NaN,Mujer,60+,NaN,...,NaN,Juan Carlos Pinzón,NaN,Voto en blanco,Sergio Fajardo,NaN,NaN,NaN,Malo / muy malo,574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
4,Atlas Intel,2026-01-09,6.080302e-07,Antioquia,Caldas,Central,NaN,Hombre,35-44,NaN,...,NaN,Voto en blanco,NaN,Voto en blanco,Voto en blanco,NaN,NaN,NaN,Malo / muy malo,574bebb8-d5bc-4a9a-b0fc-5a5471c2a8d5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44512,CNC,2026-03-16,5.157391e+03,HUILA,Timaná,Centro - Sur - Amazonía,Urbana,Mujer,35-44,2,...,Ninguno,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa,4d6479aa-58b2-4399-924c-03ffb307054d
44513,CNC,2026-03-16,2.642461e+04,RISARALDA,Pereira,Eje Cafetero,Urbana,Mujer,35-44,3,...,Luis Gilberto Murillo,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa,4d6479aa-58b2-4399-924c-03ffb307054d
44514,CNC,2026-03-16,2.966080e+04,RISARALDA,Pereira,Eje Cafetero,Urbana,Hombre,35-44,3,...,Luis Gilberto Murillo,NaN,Miguel Uribe Londoño,Paloma Valencia,NaN,NaN,NaN,NaN,Negativa,4d6479aa-58b2-4399-924c-03ffb307054d
44515,CNC,2026-03-16,2.633356e+04,"BOGOTÁ, D.C.","Bogotá, D.C.",Bogotá,Urbana,Hombre,35-44,2,...,Iván Cepeda,NaN,Iván Cepeda,Iván Cepeda,NaN,NaN,NaN,NaN,Positiva,4d6479aa-58b2-4399-924c-03ffb307054d
44516,CNC,2026-03-16,2.196748e+04,"BOGOTÁ, D.C.","Bogotá, D.C.",Bogotá,Urbana,Hombre,55+,5,...,Iván Cepeda,NaN,Iván Cepeda,Iván Cepeda,NaN,NaN,NaN,NaN,Positiva,4d6479aa-58b2-4399-924c-03ffb307054d

In [27]:
df[["encuestadora","region"]].value_counts()

encuestadora  region
Atlas Intel   Central                    10308
              Bogotá                      6581
              Caribe                      4663
              Pacífico                    3750
Invamer       Centro - Oriente            2448
              Caribe                      1728
              Eje Cafetero                1376
              Pacífico                    1216
CNC           Caribe                      1160
              Centro - Oriente             990
              Pacífico                     989
              Eje Cafetero                 969
Atlas Intel   Amazonía - Orinoquía         892
CNC           Bogotá                       830
GAD3          Central                      598
              Caribe                       543
CNC           Centro - Sur - Amazonía      524
Invamer       Centro - Sur - Amazonía      512
GAD3          Centro - Oriente             455
              Pacífico                     400
CNC           Llano                        379
GAD3          Bogotá                       375
Invamer       Llano                        320
GAD3          Amazonía - Orinoquía         102
Name: count, dtype: int64

## Análisis demográfico y sesgos

Sección para responder con código a: sesgos por encuestadora, perfil demográfico de indecisos, distribución por aprobación a Petro y comparación por edad entre primera y segunda vuelta.

In [ ]:
import pandas as pd

if 'df' not in globals():
    df = pd.read_excel("encuestas_concatenadas.xlsx")

# -----------------------------------------------------------------------------
# Herramientas para responder las preguntas demográficas del cuaderno
# -----------------------------------------------------------------------------

DEMOGRAFICAS_CANDIDATAS = [
    'sexo',
    'edad_grupo',
    'region',
    'estrato',
    'nivel_educativo',
    'educacion',
    'nivel_socioeconomico',
    'zona',
    'departamento',
    'municipio',
]

DEMOGRAFICAS = [c for c in DEMOGRAFICAS_CANDIDATAS if c in df.columns]

INDECISO_PATTERNS = (
    'no sabe',
    'no responde',
    'no votaria',
    'no votaría',
    'blanco',
    'ns/nr',
    'nsnr',
    'indeciso',
)

EDAD_EQUIV = {
    '18-24': '18-34',
    '25-34': '18-34',
    '18-34': '18-34',
    '35-44': '35-54',
    '45-54': '35-54',
    '35-54': '35-54',
    '45-59': '55+',
    '55+': '55+',
    '60+': '55+',
}

def _norm_text(value):
    if pd.isna(value):
        return ''
    return str(value).strip().lower()

def _homogeneizar_columna(subdf, col_demo):
    col_cmp = col_demo
    out = subdf.copy()
    if col_demo == 'edad_grupo':
        col_cmp = 'edad_grupo_cmp'
        out[col_cmp] = out[col_demo].astype(str).str.strip().map(EDAD_EQUIV).fillna(out[col_demo].astype(str).str.strip())
        out.loc[out[col_demo].isna(), col_cmp] = pd.NA
    return out, col_cmp

def es_indeciso(value):
    texto = _norm_text(value)
    return any(pat in texto for pat in INDECISO_PATTERNS)

def filtrar_encuesta(encuestadora=None, fecha=None):
    sub = df.copy()
    if encuestadora is not None:
        sub = sub[sub['encuestadora'] == encuestadora]
    if fecha is not None:
        sub = sub[sub['fecha'].astype(str).str.startswith(str(fecha)[:10])]
    return sub

def _weighted_pct(subdf, col):
    validos = subdf[subdf[col].notna()]
    if validos.empty:
        return pd.Series(dtype=float)
    pesos = validos.groupby(col)['factor'].sum().sort_values(ascending=False)
    return (pesos / pesos.sum() * 100).round(1)

def _homogeneizar_edad_en_df(subdf):
    out = subdf.copy()
    if 'edad_grupo' in out.columns:
        out['edad_grupo'] = out['edad_grupo'].astype(str).str.strip().map(EDAD_EQUIV).fillna(out['edad_grupo'].astype(str).str.strip())
        out.loc[out['edad_grupo'].isin(['nan', 'None', '']), 'edad_grupo'] = pd.NA
    return out

def _distribucion_por_encuesta(subdf, col_demo):
    sub2, col_cmp = _homogeneizar_columna(subdf, col_demo)
    sub2 = sub2[sub2[col_cmp].notna()].copy()
    if sub2.empty:
        return pd.DataFrame(), col_cmp

    piezas = []
    for (enc, f), grupo in sub2.groupby(['encuestadora', 'fecha']):
        dist = _weighted_pct(grupo, col_cmp)
        if dist.empty:
            continue
        tmp = dist.rename('pct').reset_index()
        tmp['encuestadora'] = enc
        tmp['fecha'] = f
        piezas.append(tmp[[col_cmp, 'encuestadora', 'fecha', 'pct']])

    if not piezas:
        return pd.DataFrame(), col_cmp
    return pd.concat(piezas, ignore_index=True), col_cmp

def _combinar_distribucion_ponderada(subdf, col_demo):
    base, col_cmp = _distribucion_por_encuesta(subdf, col_demo)
    if base.empty:
        return pd.Series(dtype=float), col_cmp
    combinado = ponderar(base, col_valor='pct', groupby=[col_cmp])
    if combinado is None or combinado.empty:
        return pd.Series(dtype=float), col_cmp
    serie = combinado.set_index(col_cmp)['pct_pond']
    total = serie.sum()
    if total > 0:
        serie = (serie / total * 100).round(1)
    return serie.sort_values(ascending=False), col_cmp

def sesgo_demografico(encuestadora, col_demo, fecha=None):
    sub = filtrar_encuesta(encuestadora=encuestadora, fecha=fecha)
    if col_demo not in sub.columns:
        return pd.DataFrame()
    ponderado, col_cmp = _combinar_distribucion_ponderada(sub, col_demo)
    sub2, col_cmp = _homogeneizar_columna(sub, col_demo)
    sin_peso = (sub2[col_cmp].value_counts(normalize=True) * 100).round(1).rename('sin_peso_pct')
    ponderado = ponderado.rename('ponderado_pct')
    tabla = pd.concat([sin_peso, ponderado], axis=1).fillna(0)
    tabla['sesgo_pp'] = (tabla['ponderado_pct'] - tabla['sin_peso_pct']).round(1)
    return tabla.sort_values('sesgo_pp', ascending=False)

def resumen_sesgos(encuestadora, top_n=5):
    resultados = {}
    for col_demo in DEMOGRAFICAS:
        tabla = sesgo_demografico(encuestadora, col_demo)
        if tabla.empty:
            continue
        resultados[col_demo] = {
            'sobrepondera': tabla['sesgo_pp'].head(top_n),
            'subpondera': tabla['sesgo_pp'].tail(top_n),
        }
    return resultados

def sesgo_relativo_vs_otras(col_demo, fecha=None):
    sub = filtrar_encuesta(fecha=fecha)
    if col_demo not in sub.columns:
        return pd.DataFrame()
    validos = sub[sub[col_demo].notna() & sub['encuestadora'].notna()].copy()
    if validos.empty:
        return pd.DataFrame()

    filas = []
    encuestadoras = sorted(validos['encuestadora'].unique())

    for enc in encuestadoras:
        sub_enc = validos[validos['encuestadora'] == enc]
        if sub_enc.empty:
            continue
        dist_enc, _ = _combinar_distribucion_ponderada(sub_enc, col_demo)
        if dist_enc.empty:
            continue

        otras = validos[validos['encuestadora'] != enc]
        dist_otras, _ = _combinar_distribucion_ponderada(otras, col_demo)
        if dist_otras.empty:
            continue

        categorias = dist_enc.index.intersection(dist_otras.index)
        if len(categorias) == 0:
            continue

        for cat in categorias:
            peso_enc = round(float(dist_enc.get(cat, 0.0)), 1)
            peso_otras = round(float(dist_otras.get(cat, 0.0)), 1)
            filas.append({
                'encuestadora': enc,
                'variable': col_demo,
                'categoria': cat,
                'peso_encuestadora': peso_enc,
                'peso_promedio_otras': peso_otras,
                'sesgo_rel_pp': round(peso_enc - peso_otras, 1),
            })

    if not filas:
        return pd.DataFrame()

    return pd.DataFrame(filas).sort_values(['variable', 'encuestadora', 'sesgo_rel_pp'], ascending=[True, True, False])

def tabla_sesgos_relativos(variables=None, fecha=None):
    if variables is None:
        variables = DEMOGRAFICAS + (['aprobacion_petro'] if 'aprobacion_petro' in df.columns else [])
    piezas = []
    for var in variables:
        t = sesgo_relativo_vs_otras(var, fecha=fecha)
        if not t.empty:
            piezas.append(t)
    if not piezas:
        return pd.DataFrame()
    return pd.concat(piezas, ignore_index=True)

def perfil_indecisos(col_demo='edad_grupo', fecha=None):
    sub = filtrar_encuesta(fecha=fecha)
    if col_demo not in sub.columns:
        return pd.DataFrame()
    indecisos = sub[sub['primera_vuelta'].apply(es_indeciso)].copy()
    if indecisos.empty:
        return pd.DataFrame()

    serie, _ = _combinar_distribucion_ponderada(indecisos, col_demo)
    if serie.empty:
        return pd.DataFrame()
    combinado = serie.rename('pct_final').to_frame()
    combinado.index.name = col_demo
    return combinado.sort_values('pct_final', ascending=False)

def votos_segun_aprobacion_petro(fecha=None, usar_pesos_encuesta=True):
    sub = filtrar_encuesta(fecha=fecha)
    if 'aprobacion_petro' not in sub.columns:
        return pd.DataFrame()
    return crosstab_ponderado(sub, 'aprobacion_petro', 'primera_vuelta', usar_pesos_encuesta=usar_pesos_encuesta)

def votos_por_edad(col_voto, fecha=None, usar_pesos_encuesta=True):
    sub = filtrar_encuesta(fecha=fecha)
    if 'edad_grupo' not in sub.columns or col_voto not in sub.columns:
        return pd.DataFrame()
    sub = _homogeneizar_edad_en_df(sub)
    return crosstab_ponderado(sub, 'edad_grupo', col_voto, usar_pesos_encuesta=usar_pesos_encuesta)
def sesgo_por_candidato(encuestadora, col_candidato='primera_vuelta', col_demo='edad_grupo', fecha=None):
    sub = filtrar_encuesta(encuestadora=encuestadora, fecha=fecha)
    if col_candidato not in sub.columns or col_demo not in sub.columns:
        return pd.DataFrame()
    if col_demo == 'edad_grupo':
        sub = _homogeneizar_edad_en_df(sub)
    return sesgo_por_candidato_df(sub, col_candidato=col_candidato, col_demo=col_demo)

def comparativo_edad_primeraysegunda():
    piezas = []
    escenarios = {
        'primera_vuelta': 'primera_vuelta',
        'cepeda_vs_abelardo': 'sv_cepeda_vs_espriella',
        'cepeda_vs_paloma': 'sv_cepeda_vs_valencia',
    }
    for nombre, columna in escenarios.items():
        tabla = votos_por_edad(columna)
        if tabla.empty:
            continue
        long = tabla.reset_index().melt(id_vars='edad_grupo', var_name='opcion', value_name='pct')
        long['escenario'] = nombre
        piezas.append(long)
    if not piezas:
        return pd.DataFrame()
    return pd.concat(piezas, ignore_index=True)

# -----------------------------------------------------------------------------
# Ejecuciones listas para inspección rápida
# -----------------------------------------------------------------------------

# 1) Sesgo relativo por encuestadora vs promedio de las otras
tabla_sesgo_relativo = tabla_sesgos_relativos()
sesgo_candidato_atlas = sesgo_por_candidato('Atlas Intel')
sesgo_candidato_gad3 = sesgo_por_candidato('GAD3')
sesgo_candidato_invamer = sesgo_por_candidato('Invamer')
sesgo_candidato_cnc = sesgo_por_candidato('CNC')

# 2) Perfil demográfico ponderado de los indecisos
indecisos_edad = perfil_indecisos('edad_grupo')
indecisos_region = perfil_indecisos('region') if 'region' in df.columns else pd.DataFrame()

# 3) Distribución de voto según aprobación a Petro
tabla_aprobacion_petro = votos_segun_aprobacion_petro()

# 4) Edad vs primera vuelta y vs las dos segundas vueltas pedidas
edad_primera_vuelta = votos_por_edad('primera_vuelta')
edad_cepeda_abelardo = votos_por_edad('sv_cepeda_vs_espriella')
edad_cepeda_paloma = votos_por_edad('sv_cepeda_vs_valencia')
comparativo_edades = comparativo_edad_primeraysegunda()
aprobacion_region_ponderada = (
    crosstab_ponderado(filtrar_encuesta(), 'region', 'aprobacion_petro', usar_pesos_encuesta=True)
    if 'region' in df.columns and 'aprobacion_petro' in df.columns else pd.DataFrame()
)

# Vistas rápidas
print('Variables demográficas disponibles:', DEMOGRAFICAS)
print('\nSesgo relativo vs otras encuestadoras (edad_grupo):')
display(tabla_sesgo_relativo[tabla_sesgo_relativo['variable'] == 'edad_grupo'].head(20))
print('\nSesgo por candidato - Atlas Intel / edad_grupo:')
display(sesgo_candidato_atlas.head(20))
print('\nPerfil final de indecisos / edad_grupo:')
display(indecisos_edad.head(10))
print('\nVoto según aprobación a Petro:')
display(tabla_aprobacion_petro.head(12))
print('\nEdad vs primera vuelta:')
display(edad_primera_vuelta.head(12))
print('\nEdad vs segunda vuelta Cepeda vs Abelardo:')
display(edad_cepeda_abelardo)
print('\nEdad vs segunda vuelta Cepeda vs Paloma:')
display(edad_cepeda_paloma)
print('\nAprobación presidencial ponderada por región:')
display(aprobacion_region_ponderada)
print('\nComparativo largo por edad:')
display(comparativo_edades.head(30))

Variables demográficas disponibles: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio']

Sesgo relativo vs otras encuestadoras (edad_grupo):

,encuestadora,variable,categoria,peso_encuestadora,peso_promedio_otras,sesgo_rel_pp
0,Atlas Intel,edad_grupo,55+,42.8,27.6,15.2
1,Atlas Intel,edad_grupo,18-34,37.5,36.9,0.6
2,Atlas Intel,edad_grupo,35-54,19.7,35.4,-15.7
3,CNC,edad_grupo,35-54,35.1,30.2,4.9
4,CNC,edad_grupo,18-34,36.6,37.2,-0.6
5,CNC,edad_grupo,55+,28.3,32.5,-4.2
6,GAD3,edad_grupo,35-54,35.4,30.1,5.3
7,GAD3,edad_grupo,18-34,36.2,37.4,-1.2
8,GAD3,edad_grupo,55+,28.3,32.5,-4.2
9,Invamer,edad_grupo,35-54,35.6,30.1,5.5
10,Invamer,edad_grupo,18-34,38.0,36.8,1.2
11,Invamer,edad_grupo,55+,26.3,33.1,-6.8

Sesgo por candidato - Atlas Intel / edad_grupo:

              primera_vuelta edad_grupo  ponderado_pct  sin_peso_pct  sesgo_pp
1   Abelardo de la Espriella      25-34           19.2          13.4       5.8
0   Abelardo de la Espriella      18-24            7.0           5.3       1.7
2   Abelardo de la Espriella      35-44           21.3          22.5      -1.2
4   Abelardo de la Espriella        60+           19.7          22.0      -2.3
3   Abelardo de la Espriella      45-59           32.7          36.8      -4.1
5             Aníbal Gaviria      18-24           40.0           9.7      30.3
8             Aníbal Gaviria      45-59           30.9          31.1      -0.2
9             Aníbal Gaviria        60+           13.8          20.4      -6.6
7             Aníbal Gaviria      35-44            9.6          20.4     -10.8
6             Aníbal Gaviria      25-34            5.6          18.4     -12.8
14                    Blanco        60+           21.6          13.8       7.8
13                    Blanco      45-59           23.9          21.6       2.3
10                    Blanco      18-24           20.2          18.1       2.1
12                    Blanco      35-44           17.1          21.6      -4.5
11                    Blanco      25-34           17.2          24.9      -7.7
18             Camilo Romero      45-59           28.8          17.5      11.3
16             Camilo Romero      25-34           45.4          35.0      10.4
15             Camilo Romero      18-24           11.5          12.5      -1.0
19             Camilo Romero        60+            0.5           7.5      -7.0
17             Camilo Romero      35-44           13.8          27.5     -13.7

Perfil final de indecisos / edad_grupo:

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Variables demográficas disponibles: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio']

Sesgo relativo vs otras encuestadoras (edad_grupo):

,encuestadora,variable,categoria,peso_encuestadora,peso_promedio_otras,sesgo_rel_pp
0,Atlas Intel,edad_grupo,55+,42.8,27.6,15.2
1,Atlas Intel,edad_grupo,18-34,37.5,36.9,0.6
2,Atlas Intel,edad_grupo,35-54,19.7,35.4,-15.7
3,CNC,edad_grupo,35-54,35.1,30.2,4.9
4,CNC,edad_grupo,18-34,36.6,37.2,-0.6
5,CNC,edad_grupo,55+,28.3,32.5,-4.2
6,GAD3,edad_grupo,35-54,35.4,30.1,5.3
7,GAD3,edad_grupo,18-34,36.2,37.4,-1.2
8,GAD3,edad_grupo,55+,28.3,32.5,-4.2
9,Invamer,edad_grupo,35-54,35.6,30.1,5.5
10,Invamer,edad_grupo,18-34,38.0,36.8,1.2
11,Invamer,edad_grupo,55+,26.3,33.1,-6.8

Sesgo por candidato - Atlas Intel / edad_grupo:

              primera_vuelta edad_grupo  ponderado_pct  sin_peso_pct  sesgo_pp
1   Abelardo de la Espriella      25-34           19.2          13.4       5.8
0   Abelardo de la Espriella      18-24            7.0           5.3       1.7
2   Abelardo de la Espriella      35-44           21.3          22.5      -1.2
4   Abelardo de la Espriella        60+           19.7          22.0      -2.3
3   Abelardo de la Espriella      45-59           32.7          36.8      -4.1
5             Aníbal Gaviria      18-24           40.0           9.7      30.3
8             Aníbal Gaviria      45-59           30.9          31.1      -0.2
9             Aníbal Gaviria        60+           13.8          20.4      -6.6
7             Aníbal Gaviria      35-44            9.6          20.4     -10.8
6             Aníbal Gaviria      25-34            5.6          18.4     -12.8
14                    Blanco        60+           21.6          13.8       7.8
13                    Blanco      45-59           23.9          21.6       2.3
10                    Blanco      18-24           20.2          18.1       2.1
12                    Blanco      35-44           17.1          21.6      -4.5
11                    Blanco      25-34           17.2          24.9      -7.7
18             Camilo Romero      45-59           28.8          17.5      11.3
16             Camilo Romero      25-34           45.4          35.0      10.4
15             Camilo Romero      18-24           11.5          12.5      -1.0
19             Camilo Romero        60+            0.5           7.5      -7.0
17             Camilo Romero      35-44           13.8          27.5     -13.7

Perfil final de indecisos / edad_grupo:

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Voto según aprobación a Petro:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,No votaría,Otro candidato,P245,Paloma Valencia,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
aprobacion_petro,,,,,,,,,,,,,,,,,,,,,
Aprueba,2.852268,0.0,0.0,0.0,0.579555,0.0,3.339531,0.0,0.0,0.0,...,0.0,0.0,0.0,4.766365,0.112914,0.964391,1.536637,0.450516,0.0,4.986492
Desaprueba,32.092192,0.0,0.0,0.0,0.489699,0.0,4.43955,0.0,0.0,0.0,...,0.0,0.0,0.0,28.116534,0.175001,1.781409,3.761006,0.3961,0.0,5.721344
Excelente / bueno,0.574929,0.032794,0.102335,0.027366,0.0,0.000282,1.224246,0.048395,0.176485,0.063667,...,0.011128,0.005019,0.0,0.225063,0.427302,0.049006,2.156635,0.001697,0.03165,1.586406
Malo / muy malo,53.599072,0.11497,0.947994,0.002486,0.0,0.305664,1.423692,0.002348,0.07868,0.145589,...,0.157024,0.013632,0.0,32.698969,0.013142,0.225567,5.293814,0.02278,0.303467,0.982909
NS/NR,11.42013,0.194988,0.0,0.0,0.010305,2.424007,4.485723,0.0,0.172474,0.0,...,0.0,0.0,0.0,15.44187,2.025337,3.458807,2.306127,0.038859,0.366927,12.057043
Negativa,29.929223,0.072771,0.0,0.0,0.07009,0.028211,4.009579,0.0,0.156667,0.068588,...,0.0,0.0,0.0,35.98992,0.259363,1.243574,4.930704,0.654591,0.262387,6.541527
P2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Positiva,3.908141,0.061062,0.0,0.0,0.402174,0.245571,3.659573,0.0,0.150124,0.04915,...,0.0,0.0,0.0,7.497843,0.589319,1.156383,2.849917,0.254472,0.146684,4.852438
Regular,11.9584,1.054692,1.451379,0.041486,0.0,0.149756,1.846954,0.007453,0.220889,0.393,...,0.537035,0.844043,0.0,14.996243,1.119876,1.962817,15.580992,0.203211,0.452551,13.5141

Variables demográficas disponibles: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio']

Sesgo relativo vs otras encuestadoras (edad_grupo):

,encuestadora,variable,categoria,peso_encuestadora,peso_promedio_otras,sesgo_rel_pp
0,Atlas Intel,edad_grupo,55+,42.8,27.6,15.2
1,Atlas Intel,edad_grupo,18-34,37.5,36.9,0.6
2,Atlas Intel,edad_grupo,35-54,19.7,35.4,-15.7
3,CNC,edad_grupo,35-54,35.1,30.2,4.9
4,CNC,edad_grupo,18-34,36.6,37.2,-0.6
5,CNC,edad_grupo,55+,28.3,32.5,-4.2
6,GAD3,edad_grupo,35-54,35.4,30.1,5.3
7,GAD3,edad_grupo,18-34,36.2,37.4,-1.2
8,GAD3,edad_grupo,55+,28.3,32.5,-4.2
9,Invamer,edad_grupo,35-54,35.6,30.1,5.5
10,Invamer,edad_grupo,18-34,38.0,36.8,1.2
11,Invamer,edad_grupo,55+,26.3,33.1,-6.8

Sesgo por candidato - Atlas Intel / edad_grupo:

              primera_vuelta edad_grupo  ponderado_pct  sin_peso_pct  sesgo_pp
1   Abelardo de la Espriella      25-34           19.2          13.4       5.8
0   Abelardo de la Espriella      18-24            7.0           5.3       1.7
2   Abelardo de la Espriella      35-44           21.3          22.5      -1.2
4   Abelardo de la Espriella        60+           19.7          22.0      -2.3
3   Abelardo de la Espriella      45-59           32.7          36.8      -4.1
5             Aníbal Gaviria      18-24           40.0           9.7      30.3
8             Aníbal Gaviria      45-59           30.9          31.1      -0.2
9             Aníbal Gaviria        60+           13.8          20.4      -6.6
7             Aníbal Gaviria      35-44            9.6          20.4     -10.8
6             Aníbal Gaviria      25-34            5.6          18.4     -12.8
14                    Blanco        60+           21.6          13.8       7.8
13                    Blanco      45-59           23.9          21.6       2.3
10                    Blanco      18-24           20.2          18.1       2.1
12                    Blanco      35-44           17.1          21.6      -4.5
11                    Blanco      25-34           17.2          24.9      -7.7
18             Camilo Romero      45-59           28.8          17.5      11.3
16             Camilo Romero      25-34           45.4          35.0      10.4
15             Camilo Romero      18-24           11.5          12.5      -1.0
19             Camilo Romero        60+            0.5           7.5      -7.0
17             Camilo Romero      35-44           13.8          27.5     -13.7

Perfil final de indecisos / edad_grupo:

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Voto según aprobación a Petro:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,No votaría,Otro candidato,P245,Paloma Valencia,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
aprobacion_petro,,,,,,,,,,,,,,,,,,,,,
Aprueba,2.852268,0.0,0.0,0.0,0.579555,0.0,3.339531,0.0,0.0,0.0,...,0.0,0.0,0.0,4.766365,0.112914,0.964391,1.536637,0.450516,0.0,4.986492
Desaprueba,32.092192,0.0,0.0,0.0,0.489699,0.0,4.43955,0.0,0.0,0.0,...,0.0,0.0,0.0,28.116534,0.175001,1.781409,3.761006,0.3961,0.0,5.721344
Excelente / bueno,0.574929,0.032794,0.102335,0.027366,0.0,0.000282,1.224246,0.048395,0.176485,0.063667,...,0.011128,0.005019,0.0,0.225063,0.427302,0.049006,2.156635,0.001697,0.03165,1.586406
Malo / muy malo,53.599072,0.11497,0.947994,0.002486,0.0,0.305664,1.423692,0.002348,0.07868,0.145589,...,0.157024,0.013632,0.0,32.698969,0.013142,0.225567,5.293814,0.02278,0.303467,0.982909
NS/NR,11.42013,0.194988,0.0,0.0,0.010305,2.424007,4.485723,0.0,0.172474,0.0,...,0.0,0.0,0.0,15.44187,2.025337,3.458807,2.306127,0.038859,0.366927,12.057043
Negativa,29.929223,0.072771,0.0,0.0,0.07009,0.028211,4.009579,0.0,0.156667,0.068588,...,0.0,0.0,0.0,35.98992,0.259363,1.243574,4.930704,0.654591,0.262387,6.541527
P2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Positiva,3.908141,0.061062,0.0,0.0,0.402174,0.245571,3.659573,0.0,0.150124,0.04915,...,0.0,0.0,0.0,7.497843,0.589319,1.156383,2.849917,0.254472,0.146684,4.852438
Regular,11.9584,1.054692,1.451379,0.041486,0.0,0.149756,1.846954,0.007453,0.220889,0.393,...,0.537035,0.844043,0.0,14.996243,1.119876,1.962817,15.580992,0.203211,0.452551,13.5141

Edad vs primera vuelta:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,Otro,Otro candidato,Paloma Valencia,Paola Holguín,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
edad_grupo,,,,,,,,,,,,,,,,,,,,,
18-24,7.5,0.0,0.0,0.0,0.9,0.1,4.5,0.0,0.2,0.1,...,0.0,0.0,14.3,0.0,0.2,3.3,3.7,0.8,0.2,8.6
18-34,13.3,0.0,0.0,0.0,0.4,0.0,4.7,0.0,0.0,0.0,...,0.0,0.0,10.9,0.0,0.0,1.1,3.2,0.0,0.0,8.1
25-34,13.7,0.1,0.0,0.0,0.2,0.1,3.6,0.0,0.1,0.1,...,0.0,0.0,18.0,0.0,0.8,1.9,3.7,0.4,0.2,6.0
35-44,17.1,0.0,0.0,0.0,0.0,0.0,3.2,0.0,0.2,0.0,...,0.0,0.0,19.2,0.0,0.4,0.9,2.5,0.2,0.2,8.2
35-54,23.9,0.0,0.0,0.0,0.2,0.2,4.2,0.0,0.0,0.0,...,0.0,0.0,15.9,0.0,0.0,0.8,3.1,0.0,0.0,5.3
45-54,18.5,0.1,0.0,0.0,0.1,0.0,4.0,0.0,0.1,0.0,...,0.0,0.0,22.6,0.0,0.3,0.8,4.1,0.3,0.2,5.8
45-59,35.9,0.3,0.6,0.0,0.0,0.0,0.5,0.0,0.1,0.3,...,0.0,0.0,22.0,0.0,1.0,0.3,3.6,0.0,0.2,2.1
55+,18.6,0.1,0.0,0.0,0.2,0.9,4.1,0.0,0.1,0.1,...,0.0,0.0,24.6,0.0,0.7,0.4,4.3,0.5,0.2,3.1
60+,31.0,0.2,1.3,0.0,0.0,0.0,2.4,0.0,0.2,0.0,...,0.0,0.9,18.1,0.0,0.3,0.0,7.3,0.0,0.1,2.1

Edad vs segunda vuelta Cepeda vs Abelardo:

sv_cepeda_vs_espriella,Abelardo de la Espriella,Iván Cepeda,NS/NR,Ninguno,No sé,No votaría,Voto en blanco
edad_grupo,,,,,,,
18-24,19.8,65.9,3.0,11.3,0.0,0.0,0.0
18-34,23.5,53.7,2.5,0.0,0.0,6.4,13.9
25-34,28.5,55.8,4.7,11.0,0.0,0.0,0.0
35-44,34.1,50.7,4.1,11.1,0.0,0.0,0.0
35-54,40.3,41.2,2.2,0.0,0.0,7.2,9.1
45-54,40.8,39.0,7.6,12.6,0.0,0.0,0.0
45-59,57.7,31.9,0.0,0.0,2.7,0.0,7.7
55+,44.9,38.7,6.4,10.0,0.0,0.0,0.0
60+,53.5,35.3,0.0,0.0,2.1,0.0,9.0

Variables demográficas disponibles: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio']

Sesgo relativo vs otras encuestadoras (edad_grupo):

,encuestadora,variable,categoria,peso_encuestadora,peso_promedio_otras,sesgo_rel_pp
0,Atlas Intel,edad_grupo,55+,42.8,27.6,15.2
1,Atlas Intel,edad_grupo,18-34,37.5,36.9,0.6
2,Atlas Intel,edad_grupo,35-54,19.7,35.4,-15.7
3,CNC,edad_grupo,35-54,35.1,30.2,4.9
4,CNC,edad_grupo,18-34,36.6,37.2,-0.6
5,CNC,edad_grupo,55+,28.3,32.5,-4.2
6,GAD3,edad_grupo,35-54,35.4,30.1,5.3
7,GAD3,edad_grupo,18-34,36.2,37.4,-1.2
8,GAD3,edad_grupo,55+,28.3,32.5,-4.2
9,Invamer,edad_grupo,35-54,35.6,30.1,5.5
10,Invamer,edad_grupo,18-34,38.0,36.8,1.2
11,Invamer,edad_grupo,55+,26.3,33.1,-6.8

Sesgo por candidato - Atlas Intel / edad_grupo:

              primera_vuelta edad_grupo  ponderado_pct  sin_peso_pct  sesgo_pp
1   Abelardo de la Espriella      25-34           19.2          13.4       5.8
0   Abelardo de la Espriella      18-24            7.0           5.3       1.7
2   Abelardo de la Espriella      35-44           21.3          22.5      -1.2
4   Abelardo de la Espriella        60+           19.7          22.0      -2.3
3   Abelardo de la Espriella      45-59           32.7          36.8      -4.1
5             Aníbal Gaviria      18-24           40.0           9.7      30.3
8             Aníbal Gaviria      45-59           30.9          31.1      -0.2
9             Aníbal Gaviria        60+           13.8          20.4      -6.6
7             Aníbal Gaviria      35-44            9.6          20.4     -10.8
6             Aníbal Gaviria      25-34            5.6          18.4     -12.8
14                    Blanco        60+           21.6          13.8       7.8
13                    Blanco      45-59           23.9          21.6       2.3
10                    Blanco      18-24           20.2          18.1       2.1
12                    Blanco      35-44           17.1          21.6      -4.5
11                    Blanco      25-34           17.2          24.9      -7.7
18             Camilo Romero      45-59           28.8          17.5      11.3
16             Camilo Romero      25-34           45.4          35.0      10.4
15             Camilo Romero      18-24           11.5          12.5      -1.0
19             Camilo Romero        60+            0.5           7.5      -7.0
17             Camilo Romero      35-44           13.8          27.5     -13.7

Perfil final de indecisos / edad_grupo:

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Voto según aprobación a Petro:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,No votaría,Otro candidato,P245,Paloma Valencia,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
aprobacion_petro,,,,,,,,,,,,,,,,,,,,,
Aprueba,2.852268,0.0,0.0,0.0,0.579555,0.0,3.339531,0.0,0.0,0.0,...,0.0,0.0,0.0,4.766365,0.112914,0.964391,1.536637,0.450516,0.0,4.986492
Desaprueba,32.092192,0.0,0.0,0.0,0.489699,0.0,4.43955,0.0,0.0,0.0,...,0.0,0.0,0.0,28.116534,0.175001,1.781409,3.761006,0.3961,0.0,5.721344
Excelente / bueno,0.574929,0.032794,0.102335,0.027366,0.0,0.000282,1.224246,0.048395,0.176485,0.063667,...,0.011128,0.005019,0.0,0.225063,0.427302,0.049006,2.156635,0.001697,0.03165,1.586406
Malo / muy malo,53.599072,0.11497,0.947994,0.002486,0.0,0.305664,1.423692,0.002348,0.07868,0.145589,...,0.157024,0.013632,0.0,32.698969,0.013142,0.225567,5.293814,0.02278,0.303467,0.982909
NS/NR,11.42013,0.194988,0.0,0.0,0.010305,2.424007,4.485723,0.0,0.172474,0.0,...,0.0,0.0,0.0,15.44187,2.025337,3.458807,2.306127,0.038859,0.366927,12.057043
Negativa,29.929223,0.072771,0.0,0.0,0.07009,0.028211,4.009579,0.0,0.156667,0.068588,...,0.0,0.0,0.0,35.98992,0.259363,1.243574,4.930704,0.654591,0.262387,6.541527
P2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Positiva,3.908141,0.061062,0.0,0.0,0.402174,0.245571,3.659573,0.0,0.150124,0.04915,...,0.0,0.0,0.0,7.497843,0.589319,1.156383,2.849917,0.254472,0.146684,4.852438
Regular,11.9584,1.054692,1.451379,0.041486,0.0,0.149756,1.846954,0.007453,0.220889,0.393,...,0.537035,0.844043,0.0,14.996243,1.119876,1.962817,15.580992,0.203211,0.452551,13.5141

Edad vs primera vuelta:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,Otro,Otro candidato,Paloma Valencia,Paola Holguín,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
edad_grupo,,,,,,,,,,,,,,,,,,,,,
18-24,7.5,0.0,0.0,0.0,0.9,0.1,4.5,0.0,0.2,0.1,...,0.0,0.0,14.3,0.0,0.2,3.3,3.7,0.8,0.2,8.6
18-34,13.3,0.0,0.0,0.0,0.4,0.0,4.7,0.0,0.0,0.0,...,0.0,0.0,10.9,0.0,0.0,1.1,3.2,0.0,0.0,8.1
25-34,13.7,0.1,0.0,0.0,0.2,0.1,3.6,0.0,0.1,0.1,...,0.0,0.0,18.0,0.0,0.8,1.9,3.7,0.4,0.2,6.0
35-44,17.1,0.0,0.0,0.0,0.0,0.0,3.2,0.0,0.2,0.0,...,0.0,0.0,19.2,0.0,0.4,0.9,2.5,0.2,0.2,8.2
35-54,23.9,0.0,0.0,0.0,0.2,0.2,4.2,0.0,0.0,0.0,...,0.0,0.0,15.9,0.0,0.0,0.8,3.1,0.0,0.0,5.3
45-54,18.5,0.1,0.0,0.0,0.1,0.0,4.0,0.0,0.1,0.0,...,0.0,0.0,22.6,0.0,0.3,0.8,4.1,0.3,0.2,5.8
45-59,35.9,0.3,0.6,0.0,0.0,0.0,0.5,0.0,0.1,0.3,...,0.0,0.0,22.0,0.0,1.0,0.3,3.6,0.0,0.2,2.1
55+,18.6,0.1,0.0,0.0,0.2,0.9,4.1,0.0,0.1,0.1,...,0.0,0.0,24.6,0.0,0.7,0.4,4.3,0.5,0.2,3.1
60+,31.0,0.2,1.3,0.0,0.0,0.0,2.4,0.0,0.2,0.0,...,0.0,0.9,18.1,0.0,0.3,0.0,7.3,0.0,0.1,2.1

Edad vs segunda vuelta Cepeda vs Abelardo:

sv_cepeda_vs_espriella,Abelardo de la Espriella,Iván Cepeda,NS/NR,Ninguno,No sé,No votaría,Voto en blanco
edad_grupo,,,,,,,
18-24,19.8,65.9,3.0,11.3,0.0,0.0,0.0
18-34,23.5,53.7,2.5,0.0,0.0,6.4,13.9
25-34,28.5,55.8,4.7,11.0,0.0,0.0,0.0
35-44,34.1,50.7,4.1,11.1,0.0,0.0,0.0
35-54,40.3,41.2,2.2,0.0,0.0,7.2,9.1
45-54,40.8,39.0,7.6,12.6,0.0,0.0,0.0
45-59,57.7,31.9,0.0,0.0,2.7,0.0,7.7
55+,44.9,38.7,6.4,10.0,0.0,0.0,0.0
60+,53.5,35.3,0.0,0.0,2.1,0.0,9.0

Edad vs segunda vuelta Cepeda vs Paloma:

sv_cepeda_vs_valencia,Iván Cepeda,NS/NR,Ninguno,No sé,No votaría,Paloma Valencia,Voto en blanco
edad_grupo,,,,,,,
18-24,61.1,2.5,10.3,0.0,0.0,26.1,0.0
18-34,51.1,3.0,0.0,0.0,5.6,28.9,11.3
25-34,50.5,3.3,10.5,0.0,0.0,35.7,0.0
35-44,47.8,3.8,9.8,0.0,0.0,38.6,0.0
35-54,40.2,2.0,0.0,0.0,6.9,43.5,7.4
45-54,37.6,5.5,10.7,0.0,0.0,46.2,0.0
45-59,32.9,0.0,0.0,3.0,0.0,51.8,12.3
55+,33.7,6.0,8.6,0.0,0.0,51.6,0.0
60+,34.9,0.0,0.0,2.2,0.0,48.3,14.6

Aprobación presidencial ponderada por región:

aprobacion_petro,Aprueba,Desaprueba,Excelente / bueno,Malo / muy malo,NS/NR,Negativa,Positiva,Regular
region,,,,,,,,
Amazonía - Orinoquía,0.0,0.0,37.3,40.7,0.0,0.0,0.0,22.0
Bogotá,0.0,0.0,0.0,0.0,3.0,45.3,51.7,0.0
Caribe,0.0,0.0,0.0,0.0,4.5,28.3,67.1,0.0
Central,0.0,0.0,28.4,55.6,0.0,0.0,0.0,16.0
Centro - Oriente,0.1,0.1,0.0,0.0,4.7,49.4,45.8,0.0
Centro - Sur - Amazonía,0.0,0.0,0.0,0.0,7.9,52.1,40.0,0.0
Eje Cafetero,0.0,0.0,0.0,0.0,6.6,59.3,34.1,0.0
Llano,0.0,0.0,0.0,0.0,6.5,49.7,43.8,0.0
Pacífico,0.0,0.0,0.0,0.0,7.1,31.4,61.4,0.0

Variables demográficas disponibles: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio']

Sesgo relativo vs otras encuestadoras (edad_grupo):

,encuestadora,variable,categoria,peso_encuestadora,peso_promedio_otras,sesgo_rel_pp
0,Atlas Intel,edad_grupo,55+,42.8,27.6,15.2
1,Atlas Intel,edad_grupo,18-34,37.5,36.9,0.6
2,Atlas Intel,edad_grupo,35-54,19.7,35.4,-15.7
3,CNC,edad_grupo,35-54,35.1,30.2,4.9
4,CNC,edad_grupo,18-34,36.6,37.2,-0.6
5,CNC,edad_grupo,55+,28.3,32.5,-4.2
6,GAD3,edad_grupo,35-54,35.4,30.1,5.3
7,GAD3,edad_grupo,18-34,36.2,37.4,-1.2
8,GAD3,edad_grupo,55+,28.3,32.5,-4.2
9,Invamer,edad_grupo,35-54,35.6,30.1,5.5
10,Invamer,edad_grupo,18-34,38.0,36.8,1.2
11,Invamer,edad_grupo,55+,26.3,33.1,-6.8

Sesgo por candidato - Atlas Intel / edad_grupo:

              primera_vuelta edad_grupo  ponderado_pct  sin_peso_pct  sesgo_pp
1   Abelardo de la Espriella      25-34           19.2          13.4       5.8
0   Abelardo de la Espriella      18-24            7.0           5.3       1.7
2   Abelardo de la Espriella      35-44           21.3          22.5      -1.2
4   Abelardo de la Espriella        60+           19.7          22.0      -2.3
3   Abelardo de la Espriella      45-59           32.7          36.8      -4.1
5             Aníbal Gaviria      18-24           40.0           9.7      30.3
8             Aníbal Gaviria      45-59           30.9          31.1      -0.2
9             Aníbal Gaviria        60+           13.8          20.4      -6.6
7             Aníbal Gaviria      35-44            9.6          20.4     -10.8
6             Aníbal Gaviria      25-34            5.6          18.4     -12.8
14                    Blanco        60+           21.6          13.8       7.8
13                    Blanco      45-59           23.9          21.6       2.3
10                    Blanco      18-24           20.2          18.1       2.1
12                    Blanco      35-44           17.1          21.6      -4.5
11                    Blanco      25-34           17.2          24.9      -7.7
18             Camilo Romero      45-59           28.8          17.5      11.3
16             Camilo Romero      25-34           45.4          35.0      10.4
15             Camilo Romero      18-24           11.5          12.5      -1.0
19             Camilo Romero        60+            0.5           7.5      -7.0
17             Camilo Romero      35-44           13.8          27.5     -13.7

Perfil final de indecisos / edad_grupo:

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Voto según aprobación a Petro:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,No votaría,Otro candidato,P245,Paloma Valencia,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
aprobacion_petro,,,,,,,,,,,,,,,,,,,,,
Aprueba,2.852268,0.0,0.0,0.0,0.579555,0.0,3.339531,0.0,0.0,0.0,...,0.0,0.0,0.0,4.766365,0.112914,0.964391,1.536637,0.450516,0.0,4.986492
Desaprueba,32.092192,0.0,0.0,0.0,0.489699,0.0,4.43955,0.0,0.0,0.0,...,0.0,0.0,0.0,28.116534,0.175001,1.781409,3.761006,0.3961,0.0,5.721344
Excelente / bueno,0.574929,0.032794,0.102335,0.027366,0.0,0.000282,1.224246,0.048395,0.176485,0.063667,...,0.011128,0.005019,0.0,0.225063,0.427302,0.049006,2.156635,0.001697,0.03165,1.586406
Malo / muy malo,53.599072,0.11497,0.947994,0.002486,0.0,0.305664,1.423692,0.002348,0.07868,0.145589,...,0.157024,0.013632,0.0,32.698969,0.013142,0.225567,5.293814,0.02278,0.303467,0.982909
NS/NR,11.42013,0.194988,0.0,0.0,0.010305,2.424007,4.485723,0.0,0.172474,0.0,...,0.0,0.0,0.0,15.44187,2.025337,3.458807,2.306127,0.038859,0.366927,12.057043
Negativa,29.929223,0.072771,0.0,0.0,0.07009,0.028211,4.009579,0.0,0.156667,0.068588,...,0.0,0.0,0.0,35.98992,0.259363,1.243574,4.930704,0.654591,0.262387,6.541527
P2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Positiva,3.908141,0.061062,0.0,0.0,0.402174,0.245571,3.659573,0.0,0.150124,0.04915,...,0.0,0.0,0.0,7.497843,0.589319,1.156383,2.849917,0.254472,0.146684,4.852438
Regular,11.9584,1.054692,1.451379,0.041486,0.0,0.149756,1.846954,0.007453,0.220889,0.393,...,0.537035,0.844043,0.0,14.996243,1.119876,1.962817,15.580992,0.203211,0.452551,13.5141

Edad vs primera vuelta:

primera_vuelta,Abelardo de la Espriella,Aníbal Gaviria,Blanco,Camilo Romero,Carlos Caicedo,Clara López,Claudia López,Daniel Palacios,Daniel Quintero,David Luna,...,Otro,Otro candidato,Paloma Valencia,Paola Holguín,Roy Barreras,Santiago Botero,Sergio Fajardo,Sondra Macollins,Vicky Dávila,Voto en blanco
edad_grupo,,,,,,,,,,,,,,,,,,,,,
18-24,7.5,0.0,0.0,0.0,0.9,0.1,4.5,0.0,0.2,0.1,...,0.0,0.0,14.3,0.0,0.2,3.3,3.7,0.8,0.2,8.6
18-34,13.3,0.0,0.0,0.0,0.4,0.0,4.7,0.0,0.0,0.0,...,0.0,0.0,10.9,0.0,0.0,1.1,3.2,0.0,0.0,8.1
25-34,13.7,0.1,0.0,0.0,0.2,0.1,3.6,0.0,0.1,0.1,...,0.0,0.0,18.0,0.0,0.8,1.9,3.7,0.4,0.2,6.0
35-44,17.1,0.0,0.0,0.0,0.0,0.0,3.2,0.0,0.2,0.0,...,0.0,0.0,19.2,0.0,0.4,0.9,2.5,0.2,0.2,8.2
35-54,23.9,0.0,0.0,0.0,0.2,0.2,4.2,0.0,0.0,0.0,...,0.0,0.0,15.9,0.0,0.0,0.8,3.1,0.0,0.0,5.3
45-54,18.5,0.1,0.0,0.0,0.1,0.0,4.0,0.0,0.1,0.0,...,0.0,0.0,22.6,0.0,0.3,0.8,4.1,0.3,0.2,5.8
45-59,35.9,0.3,0.6,0.0,0.0,0.0,0.5,0.0,0.1,0.3,...,0.0,0.0,22.0,0.0,1.0,0.3,3.6,0.0,0.2,2.1
55+,18.6,0.1,0.0,0.0,0.2,0.9,4.1,0.0,0.1,0.1,...,0.0,0.0,24.6,0.0,0.7,0.4,4.3,0.5,0.2,3.1
60+,31.0,0.2,1.3,0.0,0.0,0.0,2.4,0.0,0.2,0.0,...,0.0,0.9,18.1,0.0,0.3,0.0,7.3,0.0,0.1,2.1

Edad vs segunda vuelta Cepeda vs Abelardo:

sv_cepeda_vs_espriella,Abelardo de la Espriella,Iván Cepeda,NS/NR,Ninguno,No sé,No votaría,Voto en blanco
edad_grupo,,,,,,,
18-24,19.8,65.9,3.0,11.3,0.0,0.0,0.0
18-34,23.5,53.7,2.5,0.0,0.0,6.4,13.9
25-34,28.5,55.8,4.7,11.0,0.0,0.0,0.0
35-44,34.1,50.7,4.1,11.1,0.0,0.0,0.0
35-54,40.3,41.2,2.2,0.0,0.0,7.2,9.1
45-54,40.8,39.0,7.6,12.6,0.0,0.0,0.0
45-59,57.7,31.9,0.0,0.0,2.7,0.0,7.7
55+,44.9,38.7,6.4,10.0,0.0,0.0,0.0
60+,53.5,35.3,0.0,0.0,2.1,0.0,9.0

Edad vs segunda vuelta Cepeda vs Paloma:

sv_cepeda_vs_valencia,Iván Cepeda,NS/NR,Ninguno,No sé,No votaría,Paloma Valencia,Voto en blanco
edad_grupo,,,,,,,
18-24,61.1,2.5,10.3,0.0,0.0,26.1,0.0
18-34,51.1,3.0,0.0,0.0,5.6,28.9,11.3
25-34,50.5,3.3,10.5,0.0,0.0,35.7,0.0
35-44,47.8,3.8,9.8,0.0,0.0,38.6,0.0
35-54,40.2,2.0,0.0,0.0,6.9,43.5,7.4
45-54,37.6,5.5,10.7,0.0,0.0,46.2,0.0
45-59,32.9,0.0,0.0,3.0,0.0,51.8,12.3
55+,33.7,6.0,8.6,0.0,0.0,51.6,0.0
60+,34.9,0.0,0.0,2.2,0.0,48.3,14.6

Aprobación presidencial ponderada por región:

aprobacion_petro,Aprueba,Desaprueba,Excelente / bueno,Malo / muy malo,NS/NR,Negativa,Positiva,Regular
region,,,,,,,,
Amazonía - Orinoquía,0.0,0.0,37.3,40.7,0.0,0.0,0.0,22.0
Bogotá,0.0,0.0,0.0,0.0,3.0,45.3,51.7,0.0
Caribe,0.0,0.0,0.0,0.0,4.5,28.3,67.1,0.0
Central,0.0,0.0,28.4,55.6,0.0,0.0,0.0,16.0
Centro - Oriente,0.1,0.1,0.0,0.0,4.7,49.4,45.8,0.0
Centro - Sur - Amazonía,0.0,0.0,0.0,0.0,7.9,52.1,40.0,0.0
Eje Cafetero,0.0,0.0,0.0,0.0,6.6,59.3,34.1,0.0
Llano,0.0,0.0,0.0,0.0,6.5,49.7,43.8,0.0
Pacífico,0.0,0.0,0.0,0.0,7.1,31.4,61.4,0.0

Comparativo largo por edad:

   edad_grupo                    opcion   pct       escenario
0       18-24  Abelardo de la Espriella   7.5  primera_vuelta
1       18-34  Abelardo de la Espriella  13.3  primera_vuelta
2       25-34  Abelardo de la Espriella  13.7  primera_vuelta
3       35-44  Abelardo de la Espriella  17.1  primera_vuelta
4       35-54  Abelardo de la Espriella  23.9  primera_vuelta
5       45-54  Abelardo de la Espriella  18.5  primera_vuelta
6       45-59  Abelardo de la Espriella  35.9  primera_vuelta
7         55+  Abelardo de la Espriella  18.6  primera_vuelta
8         60+  Abelardo de la Espriella  31.0  primera_vuelta
9       18-24            Aníbal Gaviria   0.0  primera_vuelta
10      18-34            Aníbal Gaviria   0.0  primera_vuelta
11      25-34            Aníbal Gaviria   0.1  primera_vuelta
12      35-44            Aníbal Gaviria   0.0  primera_vuelta
13      35-54            Aníbal Gaviria   0.0  primera_vuelta
14      45-54            Aníbal Gaviria   0.1  primera_vuelta
15      45-59            Aníbal Gaviria   0.3  primera_vuelta
16        55+            Aníbal Gaviria   0.1  primera_vuelta
17        60+            Aníbal Gaviria   0.2  primera_vuelta
18      18-24                    Blanco   0.0  primera_vuelta
19      18-34                    Blanco   0.0  primera_vuelta
20      25-34                    Blanco   0.0  primera_vuelta
21      35-44                    Blanco   0.0  primera_vuelta
22      35-54                    Blanco   0.0  primera_vuelta
23      45-54                    Blanco   0.0  primera_vuelta
24      45-59                    Blanco   0.6  primera_vuelta
25        55+                    Blanco   0.0  primera_vuelta
26        60+                    Blanco   1.3  primera_vuelta
27      18-24             Camilo Romero   0.0  primera_vuelta
28      18-34             Camilo Romero   0.0  primera_vuelta
29      25-34             Camilo Romero   0.0  primera_vuelta

## Tablas finales y exportación

Tablas consolidadas para indecisos por demográfica, aprobación a Petro por región y exportación a Excel con una hoja por tabla.

In [29]:
def tabla_indecisos_por_demografica(col_demo, fecha=None):
    return perfil_indecisos(col_demo=col_demo, fecha=fecha)

def tablas_indecisos(fecha=None):
    tablas = {}
    for col_demo in DEMOGRAFICAS + (['aprobacion_petro'] if 'aprobacion_petro' in df.columns else []):
        tabla = tabla_indecisos_por_demografica(col_demo, fecha=fecha)
        if not tabla.empty:
            tablas[col_demo] = tabla
    return tablas

def aprobacion_por_region(fecha=None, usar_pesos_encuesta=True):
    sub = filtrar_encuesta(fecha=fecha)
    if 'region' not in sub.columns or 'aprobacion_petro' not in sub.columns:
        return pd.DataFrame()
    return crosstab_ponderado(sub, 'region', 'aprobacion_petro', usar_pesos_encuesta=usar_pesos_encuesta)

def exportar_tablas_finales(ruta=r'c:\Users\pablo\Downloads\declaraciones_senado\OneDrive_4_12-5-2026\analisis_final.xlsx'):
    tablas = {
        'sesgo_relativo': tabla_sesgo_relativo,
        'sesgo_candidato_atlas': sesgo_candidato_atlas,
        'indecisos_edad_grupo': tabla_indecisos_por_demografica('edad_grupo'),
        'indecisos_region': tabla_indecisos_por_demografica('region') if 'region' in df.columns else pd.DataFrame(),
        'indecisos_estrato': tabla_indecisos_por_demografica('estrato') if 'estrato' in df.columns else pd.DataFrame(),
        'indecisos_educacion': tabla_indecisos_por_demografica('educacion') if 'educacion' in df.columns else pd.DataFrame(),
        'indecisos_sexo': tabla_indecisos_por_demografica('sexo') if 'sexo' in df.columns else pd.DataFrame(),
        'indecisos_aprobacion_petro': tabla_indecisos_por_demografica('aprobacion_petro') if 'aprobacion_petro' in df.columns else pd.DataFrame(),
        'aprobacion_petro': tabla_aprobacion_petro,
        'aprobacion_por_region': aprobacion_por_region(),
        'edad_primera_vuelta': edad_primera_vuelta,
        'edad_cepeda_abelardo': edad_cepeda_abelardo,
        'edad_cepeda_paloma': edad_cepeda_paloma,
        'comparativo_edades': comparativo_edades,
        'df_long6': ponderar(df_long6, groupby=['escenario', 'primera_vuelta', 'voto_sv']),
    }

    with pd.ExcelWriter(ruta, engine='openpyxl') as writer:
        for nombre, tabla in tablas.items():
            if tabla is None or tabla.empty:
                continue
            if isinstance(tabla, pd.Series):
                tabla = tabla.to_frame(name='valor')
            sheet = nombre[:31]
            tabla.to_excel(writer, sheet_name=sheet)

    return tablas

# Resumen rápido para revisar en pantalla
tablas_indecisos = tablas_indecisos()
aprobacion_region = aprobacion_por_region()
print('Tablas de indecisos generadas:', list(tablas_indecisos.keys()))
display(tablas_indecisos.get('edad_grupo', pd.DataFrame()).head(10))
print('\nAprobación a Petro por región:')
display(aprobacion_region)

# Exporta el Excel final con una hoja por tabla
tablas_exportadas = exportar_tablas_finales()
print(r'Excel generado: c:\Users\pablo\Downloads\declaraciones_senado\OneDrive_4_12-5-2026\analisis_final.xlsx')

Tablas de indecisos generadas: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio', 'aprobacion_petro']

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Aprobación a Petro por región:

aprobacion_petro,Aprueba,Desaprueba,Excelente / bueno,Malo / muy malo,NS/NR,Negativa,Positiva,Regular
region,,,,,,,,
Amazonía - Orinoquía,0.0,0.0,37.3,40.7,0.0,0.0,0.0,22.0
Bogotá,0.0,0.0,0.0,0.0,3.0,45.3,51.7,0.0
Caribe,0.0,0.0,0.0,0.0,4.5,28.3,67.1,0.0
Central,0.0,0.0,28.4,55.6,0.0,0.0,0.0,16.0
Centro - Oriente,0.1,0.1,0.0,0.0,4.7,49.4,45.8,0.0
Centro - Sur - Amazonía,0.0,0.0,0.0,0.0,7.9,52.1,40.0,0.0
Eje Cafetero,0.0,0.0,0.0,0.0,6.6,59.3,34.1,0.0
Llano,0.0,0.0,0.0,0.0,6.5,49.7,43.8,0.0
Pacífico,0.0,0.0,0.0,0.0,7.1,31.4,61.4,0.0

Tablas de indecisos generadas: ['edad_grupo', 'region', 'estrato', 'educacion', 'zona', 'departamento', 'municipio', 'aprobacion_petro']

            pct_final
edad_grupo
18-34           47.70
35-44           34.11
35-54           33.70
18-24           21.38
25-34           20.50
60+             14.83
55+             13.26
45-54           10.56
45-59            9.94

Aprobación a Petro por región:

aprobacion_petro,Aprueba,Desaprueba,Excelente / bueno,Malo / muy malo,NS/NR,Negativa,Positiva,Regular
region,,,,,,,,
Amazonía - Orinoquía,0.0,0.0,37.3,40.7,0.0,0.0,0.0,22.0
Bogotá,0.0,0.0,0.0,0.0,3.0,45.3,51.7,0.0
Caribe,0.0,0.0,0.0,0.0,4.5,28.3,67.1,0.0
Central,0.0,0.0,28.4,55.6,0.0,0.0,0.0,16.0
Centro - Oriente,0.1,0.1,0.0,0.0,4.7,49.4,45.8,0.0
Centro - Sur - Amazonía,0.0,0.0,0.0,0.0,7.9,52.1,40.0,0.0
Eje Cafetero,0.0,0.0,0.0,0.0,6.6,59.3,34.1,0.0
Llano,0.0,0.0,0.0,0.0,6.5,49.7,43.8,0.0
Pacífico,0.0,0.0,0.0,0.0,7.1,31.4,61.4,0.0

Excel generado: c:\Users\pablo\Downloads\declaraciones_senado\OneDrive_4_12-5-2026\analisis_final.xlsx